import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import {
  AccordionComponent,
  BadgeComponent,
  ButtonComponent,
  CardComponent,
  CheckboxComponent,
  CodeBlockComponent,
  BreadcrumbComponent,
  ChatListComponent,
  InputComponent,
  PageBuilderComponent,
  ComponentMeta,
  ProgressComponent,
  RadioGroupComponent,
  RatingComponent,
  SeparatorComponent,
  SliderComponent,
  SparklesButtonComponent,
  SpinnerComponent,
  StreamingTextComponent,
  SwitchComponent,
  TabsComponent,
  TextareaComponent,
  TimelineComponent,
  AvatarComponent,
  AlertComponent,
} from '../../../../../packages/components/ui';
import {
  MetricWidgetComponent,
} from '../../dashboard-widgets';

@Component({
  selector: 'app-page-builder-demo',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [PageBuilderComponent],
  template: `
    <ui-page-builder [components]="pageBuilderComponents()" />
  `,
})
export class PageBuilderDemoComponent {
  readonly pageBuilderComponents = signal<ComponentMeta[]>([
    {
      id: 'card',
      name: 'Card',
      category: 'Layout',
      component: CardComponent,
      icon: 'layout',
      defaultInputs: { title: 'New Card', description: 'Card description goes here.' },
    },
    {
      id: 'tabs',
      name: 'Tabs',
      category: 'Layout',
      component: TabsComponent,
      icon: 'panels-top-left',
      defaultInputs: {},
    },
    {
      id: 'accordion',
      name: 'Accordion',
      category: 'Layout',
      component: AccordionComponent,
      icon: 'list-collapse',
      defaultInputs: {},
    },
    {
      id: 'separator',
      name: 'Separator',
      category: 'Layout',
      component: SeparatorComponent,
      icon: 'minus',
      defaultInputs: {},
    },
    {
      id: 'button',
      name: 'Button',
      category: 'Inputs',
      component: ButtonComponent,
      icon: 'box-select',
      defaultInputs: { variant: 'default', size: 'default', label: 'Click Me' },
      inputs: [
        { name: 'variant', type: 'select', options: ['default', 'destructive', 'outline', 'secondary', 'ghost', 'link'] },
        { name: 'size', type: 'select', options: ['default', 'sm', 'lg', 'icon'] },
      ],
    },
    {
      id: 'input',
      name: 'Input',
      category: 'Inputs',
      component: InputComponent,
      icon: 'text-cursor',
      defaultInputs: { placeholder: 'Type something...', value: '' },
    },
    {
      id: 'textarea',
      name: 'Textarea',
      category: 'Inputs',
      component: TextareaComponent,
      icon: 'file-text',
      defaultInputs: { placeholder: 'Start typing...', value: '' },
    },
    {
      id: 'switch',
      name: 'Switch',
      category: 'Inputs',
      component: SwitchComponent,
      icon: 'toggle-right',
      defaultInputs: { checked: false, label: 'Enable setting' },
    },
    {
      id: 'checkbox',
      name: 'Checkbox',
      category: 'Inputs',
      component: CheckboxComponent,
      icon: 'check-square',
      defaultInputs: { checked: false, label: 'Accept terms' },
    },
    {
      id: 'slider',
      name: 'Slider',
      category: 'Inputs',
      component: SliderComponent,
      icon: 'sliders-horizontal',
      defaultInputs: { value: [50], min: 0, max: 100, step: 1 },
    },
    {
      id: 'radio-group',
      name: 'Radio Group',
      category: 'Inputs',
      component: RadioGroupComponent,
      icon: 'circle-dot',
      defaultInputs: { options: ['Option 1', 'Option 2', 'Option 3'] },
    },
    {
      id: 'rating',
      name: 'Rating',
      category: 'Inputs',
      component: RatingComponent,
      icon: 'star',
      defaultInputs: { value: 3 },
    },
    {
      id: 'badge',
      name: 'Badge',
      category: 'Data Display',
      component: BadgeComponent,
      icon: 'tag',
      defaultInputs: { variant: 'default', label: 'New' },
      inputs: [{ name: 'variant', type: 'select', options: ['default', 'secondary', 'destructive', 'outline'] }],
    },
    {
      id: 'avatar',
      name: 'Avatar',
      category: 'Data Display',
      component: AvatarComponent,
      icon: 'user-circle',
      defaultInputs: { src: 'https://github.com/shadcn.png' },
    },
    {
      id: 'timeline',
      name: 'Timeline',
      category: 'Data Display',
      component: TimelineComponent,
      icon: 'clock',
      defaultInputs: {},
    },
    {
      id: 'breadcrumb',
      name: 'Breadcrumb',
      category: 'Data Display',
      component: BreadcrumbComponent,
      icon: 'chevron-right',
      defaultInputs: {},
    },
    {
      id: 'code-block',
      name: 'Code Block',
      category: 'Data Display',
      component: CodeBlockComponent,
      icon: 'code',
      defaultInputs: { code: 'console.log("Hello Page Builder!");', language: 'javascript' },
    },
    {
      id: 'alert',
      name: 'Alert',
      category: 'Feedback',
      component: AlertComponent,
      icon: 'alert-triangle',
      defaultInputs: { variant: 'default', title: 'Attention!', description: 'Something important happened.' },
      inputs: [{ name: 'variant', type: 'select', options: ['default', 'destructive'] }],
    },
    {
      id: 'progress',
      name: 'Progress',
      category: 'Feedback',
      component: ProgressComponent,
      icon: 'loader',
      defaultInputs: { value: 66 },
    },
    {
      id: 'spinner',
      name: 'Spinner',
      category: 'Feedback',
      component: SpinnerComponent,
      icon: 'refresh-cw',
      defaultInputs: { size: 'md' },
    },
    {
      id: 'metric',
      name: 'Metric',
      category: 'Advanced',
      component: MetricWidgetComponent,
      icon: 'bar-chart-2',
      defaultInputs: { title: 'Revenue', value: '$12,842', trend: 12.5 },
    },
    {
      id: 'sparkles',
      name: 'Sparkles Button',
      category: 'Advanced',
      component: SparklesButtonComponent,
      icon: 'sparkles',
      defaultInputs: { label: 'Magic Button' },
    },
    {
      id: 'chat-list',
      name: 'Chat List',
      category: 'Advanced',
      component: ChatListComponent,
      icon: 'message-square',
      defaultInputs: {},
    },
    {
      id: 'streaming-text',
      name: 'Streaming Text',
      category: 'Advanced',
      component: StreamingTextComponent,
      icon: 'type',
      defaultInputs: { text: 'This text is appearing character by character...', speed: 50 },
    },
  ]);
}
