import type { LocaleMeta } from '../../../../../packages/components/lib/i18n';

export interface ResizableDemoLocale extends LocaleMeta {
  heading: string;
  description: string;
  horizontalHeading: string;
  leftPanel: string;
  rightPanel: string;
  verticalHeading: string;
  topPanel: string;
  bottomPanel: string;
  limitsHeading: string;
  limitsCaption: string;
  limitsRange: string;
  keyboardHeading: string;
  keyboardCaption: string;
  keyboardHandleLabel: string;
  liveSizes: string;
}

export const RESIZABLE_DEMO_LOCALES: Record<string, ResizableDemoLocale> = {
  en: { code: 'en', heading: 'Resizable', description: 'Resizable panel groups for creating adjustable layouts.', horizontalHeading: 'Horizontal', leftPanel: 'Left', rightPanel: 'Right', verticalHeading: 'Vertical (with live size updates)', topPanel: 'Top', bottomPanel: 'Bottom', limitsHeading: 'Panel limits (minSize / maxSize)', limitsCaption: 'Try it: drag the divider — it stops at each panel\'s own limits.', limitsRange: 'limits', keyboardHeading: 'Keyboard resizing', keyboardCaption: 'Try it: Tab to the divider and press the arrow keys — 5% per press.', keyboardHandleLabel: 'Resize the two panels', liveSizes: 'Live sizes' },
  he: { code: 'he', rtl: true, heading: 'ניתן לשינוי גודל', description: 'קבוצות לוחות בגודל משתנה ליצירת פריסות מתכווננות.', horizontalHeading: 'אופקי', leftPanel: 'שמאל', rightPanel: 'ימין', verticalHeading: 'אנכי (עם עדכוני גודל בזמן אמת)', topPanel: 'עליון', bottomPanel: 'תחתון', limitsHeading: 'מגבלות לוח (minSize / maxSize)', limitsCaption: 'נסו: גררו את המפריד — הוא נעצר במגבלות של כל לוח בנפרד.', limitsRange: 'מגבלות', keyboardHeading: 'שינוי גודל במקלדת', keyboardCaption: 'נסו: הגיעו למפריד עם Tab ולחצו על מקשי החיצים — 5% בכל לחיצה.', keyboardHandleLabel: 'שינוי גודל שני הלוחות', liveSizes: 'גדלים בזמן אמת' },
  ar: { code: 'ar', rtl: true, heading: 'قابل لتغيير الحجم', description: 'مجموعات لوحات قابلة للتغيير لإنشاء تخطيطات قابلة للتعديل.', horizontalHeading: 'أفقي', leftPanel: 'يسار', rightPanel: 'يمين', verticalHeading: 'عمودي (مع تحديثات الحجم المباشرة)', topPanel: 'أعلى', bottomPanel: 'أسفل', limitsHeading: 'حدود اللوحة (minSize / maxSize)', limitsCaption: 'جرّب: اسحب الفاصل — يتوقف عند حدود كل لوحة على حدة.', limitsRange: 'الحدود', keyboardHeading: 'تغيير الحجم بلوحة المفاتيح', keyboardCaption: 'جرّب: انتقل إلى الفاصل بمفتاح Tab ثم اضغط مفاتيح الأسهم — 5% لكل ضغطة.', keyboardHandleLabel: 'تغيير حجم اللوحتين', liveSizes: 'الأحجام المباشرة' },
  de: { code: 'de', heading: 'Größenänderbar', description: 'Größenänderbare Panelgruppen für anpassbare Layouts.', horizontalHeading: 'Horizontal', leftPanel: 'Links', rightPanel: 'Rechts', verticalHeading: 'Vertikal (mit Live-Größenaktualisierungen)', topPanel: 'Oben', bottomPanel: 'Unten', limitsHeading: 'Panel-Grenzen (minSize / maxSize)', limitsCaption: 'Ausprobieren: Ziehen Sie den Trenner — er stoppt an den Grenzen des jeweiligen Panels.', limitsRange: 'Grenzen', keyboardHeading: 'Größenänderung per Tastatur', keyboardCaption: 'Ausprobieren: Mit Tab zum Trenner springen und die Pfeiltasten drücken — 5 % pro Druck.', keyboardHandleLabel: 'Größe beider Panels ändern', liveSizes: 'Live-Größen' },
  fr: { code: 'fr', heading: 'Redimensionnable', description: 'Groupes de panneaux redimensionnables pour créer des mises en page ajustables.', horizontalHeading: 'Horizontal', leftPanel: 'Gauche', rightPanel: 'Droite', verticalHeading: 'Vertical (avec mises à jour de taille en direct)', topPanel: 'Haut', bottomPanel: 'Bas', limitsHeading: 'Limites des panneaux (minSize / maxSize)', limitsCaption: 'À essayer : faites glisser le séparateur — il s\'arrête aux limites propres à chaque panneau.', limitsRange: 'limites', keyboardHeading: 'Redimensionnement au clavier', keyboardCaption: 'À essayer : atteignez le séparateur avec Tab et appuyez sur les flèches — 5 % par appui.', keyboardHandleLabel: 'Redimensionner les deux panneaux', liveSizes: 'Tailles en direct' },
  es: { code: 'es', heading: 'Redimensionable', description: 'Grupos de paneles redimensionables para crear diseños ajustables.', horizontalHeading: 'Horizontal', leftPanel: 'Izquierda', rightPanel: 'Derecha', verticalHeading: 'Vertical (con actualizaciones de tamaño en vivo)', topPanel: 'Arriba', bottomPanel: 'Abajo', limitsHeading: 'Límites de panel (minSize / maxSize)', limitsCaption: 'Pruébalo: arrastra el divisor — se detiene en los límites propios de cada panel.', limitsRange: 'límites', keyboardHeading: 'Redimensionar con el teclado', keyboardCaption: 'Pruébalo: llega al divisor con Tab y pulsa las flechas — 5 % por pulsación.', keyboardHandleLabel: 'Redimensionar los dos paneles', liveSizes: 'Tamaños en vivo' },
  ja: { code: 'ja', heading: 'サイズ変更可能', description: '調整可能なレイアウトを作成するためのサイズ変更可能なパネルグループ。', horizontalHeading: '水平', leftPanel: '左', rightPanel: '右', verticalHeading: '垂直（ライブサイズ更新付き）', topPanel: '上', bottomPanel: '下', limitsHeading: 'パネルの上限・下限（minSize / maxSize）', limitsCaption: '試してみる: 仕切りをドラッグすると、各パネル自身の上限・下限で止まります。', limitsRange: '範囲', keyboardHeading: 'キーボードでのサイズ変更', keyboardCaption: '試してみる: Tab キーで仕切りに移動し、矢印キーを押します（1 回につき 5%）。', keyboardHandleLabel: '2 つのパネルのサイズを変更', liveSizes: '現在のサイズ' },
  zh: { code: 'zh', heading: '可调整大小', description: '可调整大小的面板组，用于创建自适应布局。', horizontalHeading: '水平', leftPanel: '左侧', rightPanel: '右侧', verticalHeading: '垂直（实时大小更新）', topPanel: '顶部', bottomPanel: '底部', limitsHeading: '面板限制（minSize / maxSize）', limitsCaption: '试一试：拖动分隔条——它会停在每个面板各自的限制处。', limitsRange: '限制', keyboardHeading: '键盘调整大小', keyboardCaption: '试一试：用 Tab 键聚焦分隔条，然后按方向键——每次 5%。', keyboardHandleLabel: '调整两个面板的大小', liveSizes: '实时尺寸' },
  ru: { code: 'ru', heading: 'Изменяемый размер', description: 'Группы панелей с изменяемым размером для создания гибких макетов.', horizontalHeading: 'Горизонтальный', leftPanel: 'Слева', rightPanel: 'Справа', verticalHeading: 'Вертикальный (с обновлениями размера в реальном времени)', topPanel: 'Сверху', bottomPanel: 'Снизу', limitsHeading: 'Ограничения панели (minSize / maxSize)', limitsCaption: 'Попробуйте: перетащите разделитель — он останавливается на собственных пределах каждой панели.', limitsRange: 'пределы', keyboardHeading: 'Изменение размера с клавиатуры', keyboardCaption: 'Попробуйте: перейдите к разделителю клавишей Tab и нажимайте стрелки — 5 % за нажатие.', keyboardHandleLabel: 'Изменить размер двух панелей', liveSizes: 'Размеры в реальном времени' },
  pt: { code: 'pt', heading: 'Redimensionável', description: 'Grupos de painéis redimensionáveis para criar layouts ajustáveis.', horizontalHeading: 'Horizontal', leftPanel: 'Esquerda', rightPanel: 'Direita', verticalHeading: 'Vertical (com atualizações de tamanho ao vivo)', topPanel: 'Topo', bottomPanel: 'Base', limitsHeading: 'Limites do painel (minSize / maxSize)', limitsCaption: 'Experimente: arraste o divisor — ele para nos limites próprios de cada painel.', limitsRange: 'limites', keyboardHeading: 'Redimensionar pelo teclado', keyboardCaption: 'Experimente: chegue ao divisor com Tab e pressione as setas — 5% por toque.', keyboardHandleLabel: 'Redimensionar os dois painéis', liveSizes: 'Tamanhos ao vivo' },
};
