import type { LocaleMeta } from '../../../../../packages/components/lib/i18n';

export interface SidebarDemoLocale extends LocaleMeta {
  heading: string;
  description: string;
  appName: string;
  navGroup: string;
  navHome: string;
  navInbox: string;
  navCalendar: string;
  navSettings: string;
  version: string;
  mainContent: string;
  mainContentHeader: string;
  variantsHeading: string;
  variantsCaption: string;
  variantSidebarLabel: string;
  variantFloatingLabel: string;
  variantInsetLabel: string;
  variantPinnedLabel: string;
}

export const SIDEBAR_DEMO_LOCALES: Record<string, SidebarDemoLocale> = {
  en: { code: 'en', heading: 'Sidebar', description: 'A composable sidebar component for application layouts.', appName: 'My App', navGroup: 'Navigation', navHome: 'Home', navInbox: 'Inbox', navCalendar: 'Calendar', navSettings: 'Settings', version: 'v1.0.0', mainContent: 'Main content area. Click the sidebar trigger to toggle.', mainContentHeader: 'Dashboard', variantsHeading: 'Variants and pinning', variantsCaption: 'Try it: click each trigger — the first three collapse to an icon rail, the pinned one stays open.', variantSidebarLabel: 'variant="sidebar" — flush to the edge, with a dividing border', variantFloatingLabel: 'variant="floating" — detached rounded card with a shadow', variantInsetLabel: 'variant="inset" — detached, no border or shadow', variantPinnedLabel: '[collapsible]="false" — the trigger cannot collapse it' },
  he: { code: 'he', rtl: true, heading: 'סרגל צד', description: 'רכיב סרגל צד ניתן להרכבה לפריסות אפליקציה.', appName: 'האפליקציה שלי', navGroup: 'ניווט', navHome: 'בית', navInbox: 'דואר נכנס', navCalendar: 'לוח שנה', navSettings: 'הגדרות', version: 'v1.0.0', mainContent: 'אזור תוכן ראשי. לחץ על הכפתור להחלפת מצב סרגל הצד.', mainContentHeader: 'לוח בקרה', variantsHeading: 'וריאנטים ונעילה במצב פתוח', variantsCaption: 'נסו: לחצו על כל טריגר — שלושת הראשונים מתכווצים לפס אייקונים, והנעול נשאר פתוח.', variantSidebarLabel: 'variant="sidebar" — צמוד לקצה, עם גבול מפריד', variantFloatingLabel: 'variant="floating" — כרטיס מעוגל ומנותק עם צל', variantInsetLabel: 'variant="inset" — מנותק, ללא גבול וללא צל', variantPinnedLabel: '[collapsible]="false" — הטריגר לא יכול לכווץ אותו' },
  ar: { code: 'ar', rtl: true, heading: 'الشريط الجانبي', description: 'مكوّن شريط جانبي قابل للتركيب لتخطيطات التطبيقات.', appName: 'تطبيقي', navGroup: 'التنقل', navHome: 'الرئيسية', navInbox: 'صندوق الوارد', navCalendar: 'التقويم', navSettings: 'الإعدادات', version: 'v1.0.0', mainContent: 'منطقة المحتوى الرئيسية. انقر على زر الشريط الجانبي للتبديل.', mainContentHeader: 'لوحة التحكم', variantsHeading: 'الأنماط والتثبيت', variantsCaption: 'جرّب: انقر كل زر — الثلاثة الأولى تنكمش إلى شريط أيقونات، والمثبّت يبقى مفتوحًا.', variantSidebarLabel: 'variant="sidebar" — ملاصق للحافة مع حد فاصل', variantFloatingLabel: 'variant="floating" — بطاقة منفصلة بزوايا دائرية وظل', variantInsetLabel: 'variant="inset" — منفصل بلا حد ولا ظل', variantPinnedLabel: '[collapsible]="false" — لا يستطيع الزر طيّه' },
  de: { code: 'de', heading: 'Seitenleiste', description: 'Eine kompositionsfähige Seitenleiste für Anwendungslayouts.', appName: 'Meine App', navGroup: 'Navigation', navHome: 'Startseite', navInbox: 'Posteingang', navCalendar: 'Kalender', navSettings: 'Einstellungen', version: 'v1.0.0', mainContent: 'Hauptinhaltsbereich. Klicken Sie auf den Seitenleisten-Trigger zum Umschalten.', mainContentHeader: 'Dashboard', variantsHeading: 'Varianten und Fixierung', variantsCaption: 'Ausprobieren: Klicken Sie jeden Trigger — die ersten drei klappen auf eine Icon-Leiste zusammen, die fixierte bleibt offen.', variantSidebarLabel: 'variant="sidebar" — bündig am Rand, mit trennendem Rahmen', variantFloatingLabel: 'variant="floating" — abgesetzte, abgerundete Karte mit Schatten', variantInsetLabel: 'variant="inset" — abgesetzt, ohne Rahmen und Schatten', variantPinnedLabel: '[collapsible]="false" — der Trigger kann sie nicht einklappen' },
  fr: { code: 'fr', heading: 'Barre latérale', description: 'Un composant de barre latérale composable pour les mises en page d\'application.', appName: 'Mon App', navGroup: 'Navigation', navHome: 'Accueil', navInbox: 'Boîte de réception', navCalendar: 'Calendrier', navSettings: 'Paramètres', version: 'v1.0.0', mainContent: 'Zone de contenu principal. Cliquez sur le déclencheur de la barre latérale pour basculer.', mainContentHeader: 'Tableau de bord', variantsHeading: 'Variantes et épinglage', variantsCaption: 'À essayer : cliquez sur chaque déclencheur — les trois premières se réduisent à une barre d\'icônes, celle qui est épinglée reste ouverte.', variantSidebarLabel: 'variant="sidebar" — collée au bord, avec une bordure de séparation', variantFloatingLabel: 'variant="floating" — carte arrondie détachée avec une ombre', variantInsetLabel: 'variant="inset" — détachée, sans bordure ni ombre', variantPinnedLabel: '[collapsible]="false" — le déclencheur ne peut pas la réduire' },
  es: { code: 'es', heading: 'Barra lateral', description: 'Un componente de barra lateral componible para diseños de aplicaciones.', appName: 'Mi App', navGroup: 'Navegación', navHome: 'Inicio', navInbox: 'Bandeja de entrada', navCalendar: 'Calendario', navSettings: 'Ajustes', version: 'v1.0.0', mainContent: 'Área de contenido principal. Haga clic en el activador de la barra lateral para alternar.', mainContentHeader: 'Panel', variantsHeading: 'Variantes y fijación', variantsCaption: 'Pruébalo: haz clic en cada activador — las tres primeras se contraen a una barra de iconos y la fijada permanece abierta.', variantSidebarLabel: 'variant="sidebar" — pegada al borde, con un borde divisorio', variantFloatingLabel: 'variant="floating" — tarjeta redondeada separada con sombra', variantInsetLabel: 'variant="inset" — separada, sin borde ni sombra', variantPinnedLabel: '[collapsible]="false" — el activador no puede contraerla' },
  ja: { code: 'ja', heading: 'サイドバー', description: 'アプリケーションレイアウト用の組み合わせ可能なサイドバーコンポーネント。', appName: 'マイアプリ', navGroup: 'ナビゲーション', navHome: 'ホーム', navInbox: '受信トレイ', navCalendar: 'カレンダー', navSettings: '設定', version: 'v1.0.0', mainContent: 'メインコンテンツエリア。サイドバートリガーをクリックして切り替えます。', mainContentHeader: 'ダッシュボード', variantsHeading: 'バリアントと固定', variantsCaption: '試してみる: 各トリガーをクリックします。最初の 3 つはアイコンレールに折りたたまれ、固定されたものは開いたままです。', variantSidebarLabel: 'variant="sidebar" — 端に密着し、区切り線あり', variantFloatingLabel: 'variant="floating" — 浮いた角丸カード（影付き）', variantInsetLabel: 'variant="inset" — 浮いた配置で枠線も影もなし', variantPinnedLabel: '[collapsible]="false" — トリガーでは折りたためません' },
  zh: { code: 'zh', heading: '侧边栏', description: '用于应用程序布局的可组合侧边栏组件。', appName: '我的应用', navGroup: '导航', navHome: '首页', navInbox: '收件箱', navCalendar: '日历', navSettings: '设置', version: 'v1.0.0', mainContent: '主要内容区域。点击侧边栏触发器进行切换。', mainContentHeader: '仪表板', variantsHeading: '变体与固定', variantsCaption: '试一试：点击每个触发器——前三个会折叠成图标栏，被固定的那个保持展开。', variantSidebarLabel: 'variant="sidebar" — 紧贴边缘，带分隔边框', variantFloatingLabel: 'variant="floating" — 分离的圆角卡片，带阴影', variantInsetLabel: 'variant="inset" — 分离显示，无边框无阴影', variantPinnedLabel: '[collapsible]="false" — 触发器无法将其折叠' },
  ru: { code: 'ru', heading: 'Боковая панель', description: 'Компонуемый компонент боковой панели для макетов приложений.', appName: 'Моё приложение', navGroup: 'Навигация', navHome: 'Главная', navInbox: 'Входящие', navCalendar: 'Календарь', navSettings: 'Настройки', version: 'v1.0.0', mainContent: 'Основная область контента. Нажмите на триггер боковой панели для переключения.', mainContentHeader: 'Панель управления', variantsHeading: 'Варианты и закрепление', variantsCaption: 'Попробуйте: нажмите каждый триггер — первые три сворачиваются в панель значков, а закреплённая остаётся открытой.', variantSidebarLabel: 'variant="sidebar" — вплотную к краю, с разделительной границей', variantFloatingLabel: 'variant="floating" — отделённая карточка со скруглением и тенью', variantInsetLabel: 'variant="inset" — отделённая, без границы и тени', variantPinnedLabel: '[collapsible]="false" — триггер не может её свернуть' },
  pt: { code: 'pt', heading: 'Barra lateral', description: 'Um componente de barra lateral composável para layouts de aplicativos.', appName: 'Meu App', navGroup: 'Navegação', navHome: 'Início', navInbox: 'Caixa de entrada', navCalendar: 'Calendário', navSettings: 'Configurações', version: 'v1.0.0', mainContent: 'Área de conteúdo principal. Clique no gatilho da barra lateral para alternar.', mainContentHeader: 'Painel', variantsHeading: 'Variantes e fixação', variantsCaption: 'Experimente: clique em cada gatilho — os três primeiros recolhem para uma barra de ícones e o fixado permanece aberto.', variantSidebarLabel: 'variant="sidebar" — encostada à borda, com borda divisória', variantFloatingLabel: 'variant="floating" — cartão arredondado destacado com sombra', variantInsetLabel: 'variant="inset" — destacada, sem borda nem sombra', variantPinnedLabel: '[collapsible]="false" — o gatilho não consegue recolhê-la' },
};
