/**
 * Shape of `demo/public/component-docs.json`, generated by
 * `npm run docs:components` (`packages/cli/scripts/gen-component-docs.ts`).
 *
 * Declared here rather than imported from the generator so the demo app's
 * build does not depend on the CLI package's sources. `component-docs.spec.ts`
 * validates the committed payload against `isComponentDocs` below, so a shape
 * change in the generator fails a test here instead of at runtime in a browser.
 */

/** One input or output row of an API table. */
export interface ApiMemberDoc {
    readonly name: string;
    readonly type: string;
    readonly description: string;
    readonly required?: true;
    readonly default?: string;
    readonly deprecated?: string;
}

/** The API surface of one class a component ships. */
export interface ApiTableDoc {
    readonly className: string;
    readonly file: string;
    readonly kind: 'component' | 'directive';
    readonly selector: string;
    readonly description: string;
    readonly inputs: readonly ApiMemberDoc[];
    readonly outputs: readonly ApiMemberDoc[];
}

/** Everything needed to document one component. */
export interface ComponentDoc {
    readonly name: string;
    readonly description: string;
    readonly category: string;
    readonly install: string;
    readonly importStatement: string | null;
    readonly selector: string | null;
    readonly dependencies: readonly string[];
    readonly npmDependencies: readonly string[];
    readonly snippet: string | null;
    readonly snippetSkipReason: string;
    readonly demoRoute: string | null;
    readonly demoFile: string | null;
    readonly stackblitz: string | null;
    readonly api: readonly ApiTableDoc[];
}

/** The whole payload. */
export interface ComponentDocs {
    readonly version: 1;
    readonly components: readonly ComponentDoc[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null;
}

function isComponentDoc(value: unknown): value is ComponentDoc {
    if (!isRecord(value)) return false;
    return typeof value['name'] === 'string'
        && typeof value['install'] === 'string'
        && typeof value['category'] === 'string'
        && Array.isArray(value['api']);
}

/**
 * Runtime guard for a fetched payload. A stale or truncated file is a real
 * possibility (it is served as a static asset and cached by browsers), and
 * rendering half a docs page is worse than rendering none.
 */
export function isComponentDocs(value: unknown): value is ComponentDocs {
    if (!isRecord(value)) return false;
    if (value['version'] !== 1) return false;
    const components = value['components'];
    return Array.isArray(components) && components.every(isComponentDoc);
}
