/**
 * Shape of `demo/public/recipes.json`, generated by `npm run docs:recipes`
 * (`packages/cli/scripts/gen-recipes.ts`) from the compiling sources under
 * `e2e/recipes/`.
 *
 * Declared here rather than imported from the generator so the demo app's
 * build does not depend on the CLI package's sources; `recipes.spec.ts`
 * validates the committed payload against `isRecipes` below.
 */

/** One composed pattern, with the source that is proven to compile. */
export interface Recipe {
    readonly id: string;
    readonly title: string;
    readonly summary: string;
    readonly components: readonly string[];
    readonly install: string;
    readonly code: string;
    readonly file: string;
}

export interface Recipes {
    readonly version: 1;
    readonly recipes: readonly Recipe[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null;
}

function isRecipe(value: unknown): value is Recipe {
    if (!isRecord(value)) return false;
    return typeof value['id'] === 'string'
        && typeof value['title'] === 'string'
        && typeof value['summary'] === 'string'
        && typeof value['install'] === 'string'
        && typeof value['code'] === 'string'
        && Array.isArray(value['components']);
}

/** Runtime guard for the fetched payload — a truncated file must not half-render. */
export function isRecipes(value: unknown): value is Recipes {
    if (!isRecord(value)) return false;
    if (value['version'] !== 1) return false;
    const recipes = value['recipes'];
    return Array.isArray(recipes) && recipes.every(isRecipe);
}
