export const EMOJI_DATA: Record<string, string[]> = {
    // Smileys & Emotion
    '😀': ['grinning', 'face', 'smile', 'happy'],
    '😃': ['grinning', 'face', 'big', 'eyes', 'happy', 'smile'],
    '😄': ['grinning', 'face', 'smiling', 'eyes', 'happy', 'smile', 'laugh'],
    '😁': ['beaming', 'face', 'smiling', 'eyes', 'happy', 'smile', 'grin'],
    '😆': ['grinning', 'squinting', 'face', 'happy', 'smile', 'laugh'],
    '😅': ['grinning', 'face', 'sweat', 'relief', 'nervous'],
    '🤣': ['rolling', 'floor', 'laughing', 'crying', 'tears', 'lol', 'rofl'],
    '😂': ['face', 'tears', 'joy', 'cry', 'laugh', 'lol'],
    '🙂': ['slightly', 'smiling', 'face', 'smile'],
    '🙃': ['upside-down', 'face', 'silly', 'sarcasm'],
    '😉': ['winking', 'face', 'wink', 'flert'],
    '😊': ['smiling', 'face', 'smiling', 'eyes', 'happy', 'smile', 'blush'],
    '😇': ['smiling', 'face', 'halo', 'angel', 'innocent'],
    '🥰': ['smiling', 'face', 'hearts', 'love', 'crush', 'adorable'],
    '😍': ['smiling', 'face', 'heart-eyes', 'love', 'crush', 'adorable'],
    '🤩': ['star-struck', 'love', 'eyes', 'stars'],
    '😘': ['face', 'blowing', 'kiss', 'love', 'smooch'],
    '😗': ['kissing', 'face', 'love', 'smooch'],
    '☺️': ['smiling', 'face', 'blush', 'happy'],
    '😚': ['kissing', 'face', 'closed', 'eyes', 'love', 'smooch'],
    '😙': ['kissing', 'face', 'smiling', 'eyes', 'love', 'smooch'],
    '🥲': ['smiling', 'face', 'tear', 'sad', 'bittersweet'],
    '😋': ['face', 'savoring', 'food', 'yum', 'delicious', 'tongue'],
    '😛': ['face', 'tongue', 'silly', 'kidding'],
    '😜': ['winking', 'face', 'tongue', 'silly', 'kidding', 'crazy'],
    '🤪': ['zany', 'face', 'silly', 'crazy', 'goofy'],
    '😝': ['squinting', 'face', 'tongue', 'silly', 'kidding'],
    '🤑': ['money-mouth', 'face', 'rich', 'dollar'],
    '🤗': ['hugging', 'face', 'hug', 'love', 'support'],
    '🤭': ['face', 'hand', 'over', 'mouth', 'oops', 'giggle'],
    '🤫': ['shushing', 'face', 'shh', 'quiet', 'silent'],
    '🤔': ['thinking', 'face', 'hmm', 'wondering'],
    '🤐': ['zipper-mouth', 'face', 'quiet', 'silent', 'secret'],
    '🤨': ['face', 'raised', 'eyebrow', 'skeptical', 'suspicious'],
    '😐': ['neutral', 'face', 'meh', 'poker'],
    '😑': ['expressionless', 'face', 'meh'],
    '😶': ['face', 'without', 'mouth', 'silent'],
    '😏': ['smirking', 'face', 'smirk', 'flirt', 'sarcastic'],
    '😒': ['unamused', 'face', 'meh', 'bored'],
    '🙄': ['face', 'rolling', 'eyes', 'bored', 'annoyed'],
    '😬': ['grimacing', 'face', 'awkward', 'nervous'],
    '🤥': ['lying', 'face', 'pinocchio', 'liar'],
    '😌': ['relieved', 'face', 'calm', 'peaceful'],
    '😔': ['pensive', 'face', 'sad', 'thoughtful'],
    '😪': ['sleepy', 'face', 'tired', 'drowsy'],
    '🤤': ['drooling', 'face', 'hungry', 'desire'],
    '😴': ['sleeping', 'face', 'zz', 'tired', 'sleep', 'dream'],
    '😷': ['face', 'medical', 'mask', 'sick', 'covid'],
    '🤒': ['face', 'thermometer', 'sick', 'fever', 'temperature'],
    '🤕': ['face', 'head', 'bandage', 'hurt', 'injury'],
    '🤢': ['nauseated', 'face', 'sick', 'vomit'],
    '🤮': ['face', 'vomiting', 'sick', 'puke'],
    '🤧': ['sneezing', 'face', 'sick', 'cold'],
    '🥵': ['hot', 'face', 'sweating', 'heat'],
    '🥶': ['cold', 'face', 'freezing', 'ice'],
    '🥴': ['woozy', 'face', 'dizzy', 'drunk'],
    '😵': ['dizzy', 'face', 'dead'],
    '🤯': ['exploding', 'head', 'mind-blown', 'shocked'],
    '🤠': ['cowboy', 'hat', 'face', 'western'],
    '🥳': ['partying', 'face', 'celebration', 'birthday'],
    '🥸': ['disguised', 'face', 'mask'],
    '😎': ['smiling', 'face', 'sunglasses', 'cool', 'sun'],
    '🤓': ['nerd', 'face', 'glasses', 'smart'],
    '🧐': ['face', 'monocle', 'fancy', 'investigate'],
    '😕': ['confused', 'face', 'hmmm'],
    '😟': ['worried', 'face', 'concerned'],
    '🙁': ['slightly', 'frowning', 'face', 'sad'],
    '☹️': ['frowning', 'face', 'sad'],
    '😮': ['face', 'open', 'mouth', 'surprise', 'wow'],
    '😯': ['hushed', 'face', 'surprise', 'quiet'],
    '😲': ['astonished', 'face', 'shocked', 'omg'],
    '😳': ['flushed', 'face', 'embarrassed', 'blush'],
    '🥺': ['pleading', 'face', 'puppy', 'eyes', 'begging'],
    '😦': ['frowning', 'face', 'open', 'mouth', 'scared', 'surprise'],
    '😧': ['anguished', 'face', 'pain', 'suffering'],
    '😨': ['fearful', 'face', 'scared', 'afraid'],
    '😰': ['anxious', 'face', 'sweat', 'nervous'],
    '😥': ['sad', 'butt', 'relieved', 'face', 'sweat', 'phew'],
    '😢': ['crying', 'face', 'sad', 'tear'],
    '😭': ['loudly', 'crying', 'face', 'sad', 'sob'],
    '😱': ['face', 'screaming', 'fear', 'scared', 'horror'],
    '😖': ['confounded', 'face', 'frustrated'],
    '😣': ['persevering', 'face', 'struggling', 'strain'],
    '😞': ['disappointed', 'face', 'sad', 'regret'],
    '😓': ['downcast', 'face', 'sweat', 'sad', 'nervous'],
    '😩': ['weary', 'face', 'tired', 'exhausted'],
    '😫': ['tired', 'face', 'exhausted'],
    '🥱': ['yawning', 'face', 'tired', 'sleepy'],
    '😤': ['face', 'steam', 'nose', 'angry', 'mad'],
    '😡': ['pouting', 'face', 'angry', 'mad', 'red'],
    '😠': ['angry', 'face', 'mad'],
    '🤬': ['face', 'symbols', 'mouth', 'swearing', 'cursing', 'angry'],
    '😈': ['smiling', 'face', 'horns', 'devil', 'evil'],
    '👿': ['angry', 'face', 'horns', 'devil', 'evil'],
    '💀': ['skull', 'death', 'dead'],
    '☠️': ['skull', 'crossbones', 'death', 'danger', 'pirate'],
    '💩': ['pile', 'poo', 'poop', 'shit'],
    '🤡': ['clown', 'face', 'funny', 'creepy'],
    '👹': ['ogre', 'monster', 'japanese'],
    '👺': ['goblin', 'monster', 'japanese'],
    '👻': ['ghost', 'spooky', 'halloween'],
    '👽': ['alien', 'ufo', 'extraterrestrial'],
    '👾': ['alien', 'monster', 'game', 'retro'],
    '🤖': ['robot', 'bot'],
    '😺': ['grinning', 'cat', 'smile', 'happy'],
    '😸': ['grinning', 'cat', 'smiling', 'eyes', 'happy'],
    '😹': ['cat', 'tears', 'joy', 'cry', 'laugh'],
    '😻': ['smiling', 'cat', 'heart-eyes', 'love'],
    '😼': ['cat', 'wry', 'smile', 'smirk'],
    '😽': ['kissing', 'cat', 'love'],
    '🙀': ['weary', 'cat', 'scared', 'shocked'],
    '😿': ['crying', 'cat', 'sad'],
    '😾': ['pouting', 'cat', 'angry'],
    '🙈': ['see-no-evil', 'monkey', 'hide'],
    '🙉': ['hear-no-evil', 'monkey'],
    '🙊': ['speak-no-evil', 'monkey'],
    '💋': ['kiss', 'mark', 'lips', 'love'],
    '💌': ['love', 'letter', 'email', 'heart'],
    '💘': ['heart', 'arrow', 'love', 'cupid'],
    '💝': ['heart', 'ribbon', 'gift', 'love'],
    '💖': ['sparkling', 'heart', 'love'],
    '💗': ['growing', 'heart', 'love', 'pulse'],
    '💓': ['beating', 'heart', 'love', 'pulse'],
    '💞': ['revolving', 'hearts', 'love'],
    '💕': ['two', 'hearts', 'love'],
    '💟': ['heart', 'decoration', 'love'],
    '❣️': ['heart', 'exclamation', 'love'],
    '💔': ['broken', 'heart', 'sad', 'breakup'],
    '❤️': ['red', 'heart', 'love'],
    '🧡': ['orange', 'heart', 'love'],
    '💛': ['yellow', 'heart', 'love'],
    '💚': ['green', 'heart', 'love'],
    '💙': ['blue', 'heart', 'love'],
    '💜': ['purple', 'heart', 'love'],
    '🤎': ['brown', 'heart', 'love'],
    '🖤': ['black', 'heart', 'love', 'goth'],
    '🤍': ['white', 'heart', 'love', 'peace'],
    '💯': ['hundred', 'points', 'score', 'perfect'],
    '💢': ['anger', 'symbol', 'mad'],
    '💥': ['collision', 'boom', 'explode'],
    '💫': ['dizzy', 'star', 'sparkle'],
    '💦': ['sweat', 'droplets', 'water'],
    '💨': ['dashing', 'away', 'wind', 'fast'],
    '🕳️': ['hole'],
    '💣': ['bomb', 'explode'],
    '💬': ['speech', 'balloon', 'chat', 'message'],
    '👁️‍🗨️': ['eye', 'speech', 'bubble'],
    '🗨️': ['left', 'speech', 'bubble'],
    '🗯️': ['right', 'anger', 'bubble'],
    '💭': ['thought', 'balloon', 'think', 'dream'],
    '💤': ['zzz', 'sleep', 'sleeping'],

    // People & Body
    '👋': ['waving', 'hand', 'hello', 'bye'],
    '🤚': ['raised', 'back', 'hand'],
    '🖐️': ['hand', 'fingers', 'splayed'],
    '✋': ['raised', 'hand', 'stop', 'high-five'],
    '🖖': ['vulcan', 'salute', 'star', 'trek', 'prosper'],
    '👌': ['ok', 'hand', 'okay', 'perfect'],
    '🤌': ['pinched', 'fingers', 'italian'],
    '🤏': ['pinching', 'hand', 'small', 'little'],
    '✌️': ['victory', 'hand', 'peace'],
    '🤞': ['crossed', 'fingers', 'luck'],
    '🤟': ['love-you', 'gesture', 'ily'],
    '🤘': ['sign', 'horns', 'rock', 'metal'],
    '🤙': ['call', 'me', 'hand', 'phone'],
    '👈': ['backhand', 'index', 'pointing', 'left'],
    '👉': ['backhand', 'index', 'pointing', 'right'],
    '👆': ['backhand', 'index', 'pointing', 'up'],
    '🖕': ['middle', 'finger', 'rude'],
    '👇': ['backhand', 'index', 'pointing', 'down'],
    '☝️': ['index', 'pointing', 'up'],
    '👍': ['thumbs', 'up', 'approve', 'like', 'good', 'yes'],
    '👎': ['thumbs', 'down', 'disapprove', 'dislike', 'bad', 'no'],
    '✊': ['raised', 'fist', 'power'],
    '👊': ['oncoming', 'fist', 'punch'],
    '🤛': ['left-facing', 'fist', 'punch'],
    '🤜': ['right-facing', 'fist', 'punch'],
    '👏': ['clapping', 'hands', 'applause'],
    '🙌': ['raising', 'hands', 'celebration'],
    '👐': ['open', 'hands'],
    '🤲': ['palms', 'up', 'together', 'pray'],
    '🤝': ['handshake', 'deal', 'agree'],
    '🙏': ['folded', 'hands', 'pray', 'please', 'thanks'],
    '✍️': ['writing', 'hand'],
    '💅': ['nail', 'polish', 'manicure'],
    '🤳': ['selfie'],
    '💪': ['flexed', 'biceps', 'muscle', 'strong'],
    '🦾': ['mechanical', 'arm'],
    '🦿': ['mechanical', 'leg'],
    '🦵': ['leg'],
    '🦶': ['foot'],
    '👂': ['ear', 'listen'],
    '🦻': ['ear', 'hearing', 'aid'],
    '👃': ['nose', 'smell'],
    '🧠': ['brain', 'smart'],
    '🫀': ['anatomical', 'heart'],
    '🫁': ['lungs'],
    '🦷': ['tooth', 'dentist'],
    '🦴': ['bone'],
    '👀': ['eyes', 'look', 'see'],
    '👁️': ['eye'],
    '👅': ['tongue'],
    '👄': ['mouth', 'lips'],
    '👶': ['baby', 'child'],
    '🧒': ['child', 'kid'],
    '👦': ['boy'],
    '👧': ['girl'],
    '🧑': ['person', 'human'],
    '👱': ['person', 'blond', 'hair'],
    '👨': ['man'],
    '🧔': ['person', 'beard'],
    '👩': ['woman'],
    '🧓': ['older', 'person'],
    '👴': ['old', 'man'],
    '👵': ['old', 'woman'],
    '🙍': ['person', 'frowning'],
    '🙎': ['person', 'pouting'],
    '🙅': ['person', 'gesturing', 'no'],
    '🙆': ['person', 'gesturing', 'ok'],
    '💁': ['person', 'tipping', 'hand', 'sassy'],
    '🙋': ['person', 'raising', 'hand'],
    '🧏': ['deaf', 'person'],
    '🙇': ['person', 'bowing', 'apology'],
    '🤦': ['person', 'facepalming', 'doh'],
    '🤷': ['person', 'shrugging', 'idk'],
    '👮': ['police', 'officer', 'cop'],
    '🕵️': ['detective', 'spy'],
    '💂': ['guard'],
    '🥷': ['ninja'],
    '👷': ['construction', 'worker'],
    '🤴': ['prince'],
    '👸': ['princess'],
    '👳': ['person', 'turban'],
    '👲': ['person', 'skullcap'],
    '🧕': ['woman', 'headscarf'],
    '🤵': ['person', 'tuxedo', 'groom'],
    '👰': ['person', 'veil', 'bride'],
    '🤰': ['pregnant', 'woman'],
    '🤱': ['breast-feeding'],
    '👼': ['baby', 'angel'],
    '🎅': ['santa', 'claus'],
    '🤶': ['mrs', 'claus'],
    '🦸': ['superhero'],
    '🦹': ['supervillain'],
    '🧙': ['mage', 'wizard'],
    '🧚': ['fairy'],
    '🧛': ['vampire'],
    '🧜': ['merperson', 'mermaid'],
    '🧝': ['elf'],
    '🧞': ['genie'],
    '🧟': ['zombie'],
    '💆': ['person', 'getting', 'massage'],
    '💇': ['person', 'getting', 'haircut'],
    '🚶': ['person', 'walking'],
    '🧍': ['person', 'standing'],
    '🧎': ['person', 'kneeling'],
    '🏃': ['person', 'running'],
    '💃': ['woman', 'dancing'],
    '🕺': ['man', 'dancing'],
    '🕴️': ['person', 'suit', 'levitating'],
    '👯': ['people', 'partying', 'bunny'],
    '🧖': ['person', 'steamy', 'room', 'sauna'],
    '👭': ['women', 'holding', 'hands'],
    '👫': ['woman', 'man', 'holding', 'hands'],
    '👬': ['men', 'holding', 'hands'],
    '💏': ['kiss'],
    '💑': ['couple', 'heart'],
    '👪': ['family'],
    '👨‍👩‍👦': ['family', 'man', 'woman', 'boy'],
    '👨‍👩‍👧': ['family', 'man', 'woman', 'girl'],
    '👨‍👩‍👧‍👦': ['family', 'man', 'woman', 'girl', 'boy'],
    '👨‍👩‍👦‍👦': ['family', 'man', 'woman', 'boy', 'boy'],

    // Animals & Nature
    '🐶': ['dog', 'face', 'puppy', 'pet'],
    '🐱': ['cat', 'face', 'kitten', 'pet'],
    '🐭': ['mouse', 'face'],
    '🐹': ['hamster'],
    '🐰': ['rabbit', 'face', 'bunny'],
    '🦊': ['fox'],
    '🐻': ['bear'],
    '🐼': ['panda'],
    '🐻‍❄️': ['polar', 'bear'],
    '🐨': ['koala'],
    '🐯': ['tiger', 'face'],
    '🦁': ['lion'],
    '🐮': ['cow', 'face'],
    '🐷': ['pig', 'face'],
    '🐽': ['pig', 'nose'],
    '🐸': ['frog'],
    '🐵': ['monkey', 'face'],
    '🐒': ['monkey'],
    '🐔': ['chicken'],
    '🐧': ['penguin'],
    '🐦': ['bird'],
    '🐤': ['baby', 'chick'],
    '🐣': ['hatching', 'chick'],
    '🐥': ['front-facing', 'baby', 'chick'],
    '🦆': ['duck'],
    '🦅': ['eagle'],
    '🦉': ['owl'],
    '🦇': ['bat'],
    '🐺': ['wolf'],
    '🐗': ['boar'],
    '🐴': ['horse', 'face'],
    '🦄': ['unicorn'],
    '🐝': ['honeybee', 'bee'],
    '🪱': ['worm'],
    '🐛': ['bug'],
    '🦋': ['butterfly'],
    'snail': ['snail'], // 🐌 missed in mapping but char is sufficient?
    '🐌': ['snail'],
    '🐞': ['lady_beetle', 'ladybug'],
    '🐜': ['ant'],
    '🪰': ['fly'],
    '🪲': ['beetle'],
    '🪳': ['cockroach'],
    '🦟': ['mosquito'],
    '🦗': ['cricket'],
    '🕷️': ['spider'],
    '🕸️': ['spider', 'web'],
    '🦂': ['scorpion'],
    '🐢': ['turtle'],
    '🐍': ['snake'],
    '🦎': ['lizard'],
    '🦖': ['t-rex', 'dinosaur'],
    '🦕': ['sauropod', 'dinosaur'],
    '🐙': ['octopus'],
    '🦑': ['squid'],
    '🦐': ['shrimp'],
    '🦞': ['lobster'],
    '🦀': ['crab'],
    '🐡': ['blowfish'],
    '🐠': ['tropical', 'fish'],
    '🐟': ['fish'],
    '🐬': ['dolphin'],
    '🐳': ['spouting', 'whale'],
    '🐋': ['whale'],
    '🦈': ['shark'],
    '🐊': ['crocodile'],
    '🐅': ['tiger'],
    '🐆': ['leopard'],
    '🦓': ['zebra'],
    '🦍': ['gorilla'],
    '🦧': ['orangutan'],
    '🦣': ['mammoth'],
    '🐘': ['elephant'],
    '🦛': ['hippopotamus'],
    '🦏': ['rhinoceros'],
    '🐪': ['camel', 'one', 'hump'],
    '🐫': ['camel', 'two', 'humps'],
    '🦒': ['giraffe'],
    '🦘': ['kangaroo'],
    '🦬': ['bison'],
    '🐃': ['water', 'buffalo'],
    '🐂': ['ox'],
    '🐄': ['cow'],
    '🐎': ['horse'],
    '🐖': ['pig'],
    '🐏': ['ram'],
    '🐑': ['sheep'],
    '🦙': ['llama'],
    '🐐': ['goat'],
    '🦌': ['deer'],
    '🐕': ['dog'],
    '🐩': ['poodle'],
    '🦮': ['guide', 'dog'],
    '🐕‍🦺': ['service', 'dog'],
    '🐈': ['cat'],
    '🐈‍⬛': ['black', 'cat'],
    '🪶': ['feather'],
    '🐓': ['rooster'],
    '🦃': ['turkey'],
    '🦤': ['dodo'],
    '🦚': ['peacock'],
    'parrot': ['parrot'],
    '🦜': ['parrot'],
    '🦢': ['swan'],
    '🦩': ['flamingo'],
    '🕊️': ['dove', 'peace'],
    '🐇': ['rabbit', 'bunny'],
    '🦝': ['raccoon'],
    '🦨': ['skunk'],
    '🦡': ['badger'],
    '🦫': ['beaver'],
    '🦦': ['otter'],
    '🦥': ['sloth'],
    '🐁': ['mouse'],
    '🐀': ['rat'],
    '🐿️': ['chipmunk'],
    '🦔': ['hedgehog'],
    '🌵': ['cactus'],
    '🎄': ['christmas', 'tree'],
    '🌲': ['evergreen', 'tree'],
    '🌳': ['deciduous', 'tree'],
    '🌴': ['palm', 'tree'],
    '🪵': ['wood'],
    '🌱': ['seedling', 'plant'],
    '🌿': ['herb'],
    '☘️': ['shamrock'],
    '🍀': ['four', 'leaf', 'clover', 'luck'],
    '🎍': ['pine', 'decoration'],
    '🪴': ['potted', 'plant'],
    '🎋': ['tanabata', 'tree'],
    '🍃': ['leaves', 'wind'],
    '🍂': ['fallen', 'leaf'],
    '🍁': ['maple', 'leaf'],
    '🍄': ['mushroom'],
    '🐚': ['shell'],
    '🪨': ['rock'],
    '🌾': ['sheaf', 'rice'],
    '💐': ['bouquet', 'flowers'],
    '🌷': ['tulip'],
    '🌹': ['rose'],
    '🥀': ['wilted', 'flower'],
    '🌺': ['hibiscus'],
    '🌸': ['cherry', 'blossom'],
    '🌼': ['blossom'],
    '🌻': ['sunflower'],
    '🌞': ['sun', 'face'],
    '🌝': ['full', 'moon', 'face'],
    '🌛': ['first', 'quarter', 'moon', 'face'],
    '🌜': ['last', 'quarter', 'moon', 'face'],
    '🌚': ['new', 'moon', 'face'],
    '🌕': ['full', 'moon'],
    '🌖': ['waning', 'gibbous', 'moon'],
    '🌗': ['last', 'quarter', 'moon'],
    '🌘': ['waning', 'crescent', 'moon'],
    '🌑': ['new', 'moon'],
    '🌒': ['waxing', 'crescent', 'moon'],
    '🌓': ['first', 'quarter', 'moon'],
    '🌔': ['waxing', 'gibbous', 'moon'],
    '🌙': ['crescent', 'moon'],
    '🌎': ['globe', 'americas'],
    '🌍': ['globe', 'europe', 'africa'],
    '🌏': ['globe', 'asia', 'australia'],
    '🪐': ['ringed', 'planet'],
    '⭐': ['star'],
    '🌟': ['glowing', 'star'],
    '✨': ['sparkles'],
    '⚡': ['high', 'voltage', 'lightning'],
    '☄️': ['comet'],
    '🔥': ['fire', 'hot', 'flame'],
    '🌪️': ['tornado'],
    '🌈': ['rainbow'],
    '☀️': ['sun'],
    '🌤️': ['sun', 'small', 'cloud'],
    '⛅': ['sun', 'behind', 'cloud'],
    '🌥️': ['sun', 'large', 'cloud'],
    '☁️': ['cloud'],
    '🌦️': ['sun', 'rain'],
    '🌧️': ['cloud', 'rain'],
    '⛈️': ['cloud', 'lightning', 'rain'],
    '🌩️': ['cloud', 'lightning'],
    '🌨️': ['cloud', 'snow'],
    '❄️': ['snowflake'],
    '☃️': ['snowman'],
    '⛄': ['snowman', 'without', 'snow'],
    '🌬️': ['wind', 'face'],
    '💧': ['droplet', 'water'],
    '☔': ['umbrella', 'rain'],
    '☂️': ['umbrella'],
    '🌊': ['wave', 'ocean'],
    '🌫️': ['fog'],

    // Food & Drink (Partial, common ones)
    '🍇': ['grapes'],
    '🍈': ['melon'],
    '🍉': ['watermelon'],
    '🍊': ['tangerine', 'orange'],
    '🍋': ['lemon'],
    '🍌': ['banana'],
    '🍍': ['pineapple'],
    '🥭': ['mango'],
    '🍎': ['red', 'apple'],
    '🍏': ['green', 'apple'],
    '🍐': ['pear'],
    '🍑': ['peach', 'butt', 'ass'],
    '🍒': ['cherries'],
    '🍓': ['strawberry'],
    '🫐': ['blueberries'],
    '🥝': ['kiwi'],
    '🍅': ['tomato'],
    '🫒': ['olive'],
    '🥥': ['coconut'],
    '🥑': ['avocado'],
    '🍆': ['eggplant'],
    '🥔': ['potato'],
    '🥕': ['carrot'],
    '🌽': ['corn'],
    '🌶️': ['hot', 'pepper', 'spicy'],
    '🫑': ['bell', 'pepper'],
    '🥒': ['cucumber'],
    '🥬': ['leafy', 'green'],
    '🥦': ['broccoli'],
    '🧄': ['garlic'],
    '🧅': ['onion'],
    '🥜': ['peanuts'],
    '🌰': ['chestnut'],
    '🍞': ['bread'],
    '🥐': ['croissant', 'quaso'],
    '🥖': ['baguette'],
    '🫓': ['flatbread'],
    '🥨': ['pretzel'],
    '🥯': ['bagel'],
    '🥞': ['pancakes'],
    '🧇': ['waffle'],
    '🧀': ['cheese'],
    '🍖': ['meat', 'bone'],
    '🍗': ['poultry', 'leg', 'chicken'],
    '🥩': ['cut', 'meat', 'steak'],
    '🥓': ['bacon'],
    '🍔': ['hamburger', 'burger'],
    '🍟': ['french', 'fries'],
    '🍕': ['pizza'],
    '🌭': ['hot', 'dog'],
    '🥪': ['sandwich'],
    '🌮': ['taco'],
    '🌯': ['burrito'],
    '🫔': ['tamale'],
    '🥙': ['stuffed', 'flatbread', 'pita'],
    '🧆': ['falafel'],
    '🥚': ['egg'],
    '🍳': ['cooking'],
    '🥘': ['shallow', 'pan', 'food'],
    '🍲': ['pot', 'food'],
    '🫕': ['fondue'],
    '🥣': ['bowl', 'spoon'],
    '🥗': ['green', 'salad'],
    '🍿': ['popcorn'],
    '🧈': ['butter'],
    '🧂': ['salt'],
    '🥫': ['canned', 'food'],
    '🍱': ['bento', 'box'],
    '🍘': ['rice', 'cracker'],
    '🍙': ['rice', 'ball'],
    '🍚': ['cooked', 'rice'],
    '🍛': ['curry', 'rice'],
    '🍜': ['steaming', 'bowl', 'noodles', 'ramen'],
    '🍝': ['spaghetti', 'pasta'],
    '🍠': ['roasted', 'sweet', 'potato'],
    '🍢': ['oden'],
    '🍣': ['sushi'],
    '🍤': ['fried', 'shrimp', 'tempura'],
    '🍥': ['fish', 'cake'],
    '🥮': ['moon', 'cake'],
    '🍡': ['dango'],
    '🥟': ['dumpling'],
    '🥠': ['fortune', 'cookie'],
    '🥡': ['takeout', 'box'],
    '🦪': ['oyster'],
    '🍦': ['soft', 'ice', 'cream'],
    '🍧': ['shaved', 'ice'],
    '🍨': ['ice', 'cream'],
    '🍩': ['doughnut'],
    '🍪': ['cookie'],
    '🎂': ['birthday', 'cake'],
    '🍰': ['shortcake'],
    '🧁': ['cupcake'],
    '🥧': ['pie'],
    '🍫': ['chocolate', 'bar'],
    '🍬': ['candy'],
    '🍭': ['lollipop'],
    '🍮': ['custard'],
    '🍯': ['honey', 'pot'],
    '🍼': ['baby', 'bottle'],
    '🥛': ['glass', 'milk'],
    '☕': ['hot', 'beverage', 'coffee', 'tea'],
    '🫖': ['teapot'],
    '🍵': ['teacup'],
    '🍶': ['sake'],
    '🍾': ['champagne'],
    '🍷': ['wine'],
    '🍸': ['cocktail'],
    '🍹': ['tropical', 'drink'],
    '🍺': ['beer', 'mug'],
    '🍻': ['clinking', 'beer', 'mugs'],
    '🥂': ['clinking', 'glasses', 'cheers'],
    '🥃': ['tumbler', 'glass', 'whiskey'],
    '🥤': ['cup', 'straw'],
    '🧋': ['bubble', 'tea'],
    '🧃': ['beverage', 'box', 'juice'],
    '🧉': ['mate'],
    '🧊': ['ice'],
    '🥢': ['chopsticks'],
    '🍽️': ['fork', 'knife', 'plate'],
    '🍴': ['fork', 'knife'],
    'spoon': ['spoon'], // 🥄
    '🥄': ['spoon'],
    '🔪': ['kitchen', 'knife'],
    '🏺': ['amphora'],

    // Activities
    '⚽': ['soccer'],
    '🏀': ['basketball'],
    '🏈': ['american', 'football'],
    '⚾': ['baseball'],
    '🥎': ['softball'],
    '🎾': ['tennis'],
    '🏐': ['volleyball'],
    '🏉': ['rugby'],
    '🥏': ['flying', 'disc', 'frisbee'],
    '🎱': ['pool', '8', 'ball'],
    '🪀': ['yo-yo'],
    '🏓': ['ping', 'pong', 'table', 'tennis'],
    '🏸': ['badminton'],
    '🏒': ['ice', 'hockey'],
    '🏑': ['field', 'hockey'],
    '🥍': ['lacrosse'],
    '🏏': ['cricket'],
    '🪃': ['boomerang'],
    '🥅': ['goal', 'net'],
    '⛳': ['flag', 'hole', 'golf'],
    'kite': ['kite'], // 🪁
    '🪁': ['kite'],
    '🏹': ['bow', 'arrow'],
    '🎣': ['fishing', 'pole'],
    '🤿': ['diving', 'mask'],
    '🥊': ['boxing', 'glove'],
    '🥋': ['martial', 'arts', 'uniform'],
    '🎽': ['running', 'shirt'],
    'skateboard': ['skateboard'], // 🛹
    '🛹': ['skateboard'],
    '🛼': ['roller', 'skate'],
    '🛷': ['sled'],
    '⛸️': ['ice', 'skate'],
    '🥌': ['curling', 'stone'],
    '🎿': ['skis'],
    '⛷️': ['skier'],
    '🏂': ['snowboarder'],
    '🪂': ['parachute'],
    '🏋️': ['person', 'lifting', 'weights'],
    '🤼': ['people', 'wrestling'],
    '🤸': ['person', 'cartwheeling'],
    '⛹️': ['person', 'bouncing', 'ball'],
    '🤺': ['person', 'fencing'],
    '🤾': ['person', 'playing', 'handball'],
    '🏌️': ['person', 'golfing'],
    '🏇': ['horse', 'racing'],
    '🧗': ['person', 'climbing'],
    '🤽': ['person', 'playing', 'water', 'polo'],
    '🏊': ['person', 'swimming'],
    '🚣': ['person', 'rowing', 'boat'],
    '🧘': ['person', 'lotus', 'position', 'yoga'],
    '🏄': ['person', 'surfing'],
    '🏆': ['trophy', 'winner'],
    '🥇': ['1st', 'place', 'medal'],
    '🥈': ['2nd', 'place', 'medal'],
    '🥉': ['3rd', 'place', 'medal'],
    '🏅': ['sports', 'medal'],
    '🎖️': ['military', 'medal'],
    '🏵️': ['rosette'],
    '🎗️': ['reminder', 'ribbon'],
    'ticket': ['ticket'], // 🎫
    '🎫': ['ticket'],
    '🎟️': ['admission', 'tickets'],
    'circus': ['circus', 'tent'], // 🎪
    '🎪': ['circus', 'tent'],
    '🤹': ['person', 'juggling'],
    '🎭': ['performing', 'arts'],
    '🩰': ['ballet', 'shoes'],
    '🎨': ['artist', 'palette'],
    '🎬': ['clapper', 'board'],
    '🎤': ['microphone'],
    '🎧': ['headphone'],
    '🎼': ['musical', 'score'],
    '🎹': ['musical', 'keyboard', 'piano'],
    '🥁': ['drum'],
    '🪘': ['long', 'drum'],
    'sax': ['saxophone'], // 🎷
    '🎷': ['saxophone'],
    '🎺': ['trumpet'],
    '🪗': ['accordion'],
    '🎸': ['guitar'],
    '🪕': ['banjo'],
    '🎻': ['violin'],
    '🎲': ['game', 'die'],
    '♟️': ['chess', 'pawn'],
    '🎯': ['bullseye', 'dart'],
    '🎳': ['bowling'],
    '🎮': ['video', 'game', 'controller'],
    '🎰': ['slot', 'machine'],
    '🧩': ['puzzle', 'piece'],

    // Travel & Places
    '🚗': ['car', 'automobile'],
    'taxi': ['taxi'], // 🚕
    '🚕': ['taxi'],
    '🚙': ['suv', 'recreational', 'vehicle'],
    'bus': ['bus'], // 🚌
    '🚌': ['bus'],
    '🚎': ['trolleybus'],
    '🏎️': ['racing', 'car'],
    '🚓': ['police', 'car'],
    '🚑': ['ambulance'],
    '🚒': ['fire', 'engine'],
    '🚐': ['minibus'],
    '🛻': ['pickup', 'truck'],
    '🚚': ['delivery', 'truck'],
    '🚛': ['articulated', 'lorry'],
    '🚜': ['tractor'],
    '🦯': ['guide', 'white', 'cane'],
    '🦽': ['manual', 'wheelchair'],
    '🦼': ['motorized', 'wheelchair'],
    'scooter': ['scooter'], // 🛴
    '🛴': ['scooter'],
    'bicycle': ['bicycle', 'bike'], // 🚲
    '🚲': ['bicycle', 'bike'],
    '🛵': ['motor', 'scooter'],
    '🏍️': ['motorcycle'],
    '🛺': ['auto', 'rickshaw'],
    '🚨': ['police', 'car', 'light', 'siren'],
    '🚔': ['oncoming', 'police', 'car'],
    '🚍': ['oncoming', 'bus'],
    '🚘': ['oncoming', 'automobile'],
    '🚖': ['oncoming', 'taxi'],
    '🚡': ['aerial', 'tramway'],
    '🚠': ['mountain', 'cableway'],
    '🚟': ['suspension', 'railway'],
    'railway': ['railway', 'car'], // 🚃
    '🚃': ['railway', 'car'],
    'tram': ['tram', 'car'], // 🚋
    '🚋': ['tram', 'car'],
    '🚞': ['mountain', 'railway'],
    '🚝': ['monorail'],
    '🚄': ['high-speed', 'train'],
    '🚅': ['bullet', 'train'],
    '🚈': ['light', 'rail'],
    '🚂': ['locomotive'],
    '🚆': ['train'],
    '🚇': ['metro'],
    '🚊': ['tram'],
    '🚉': ['station'],
    '✈️': ['airplane'],
    '🛫': ['airplane', 'departure'],
    '🛬': ['airplane', 'arrival'],
    '🛩️': ['small', 'airplane'],
    '💺': ['seat'],
    '🛰️': ['satellite'],
    '🚀': ['rocket'],
    '🛸': ['flying', 'saucer', 'ufo'],
    '🚁': ['helicopter'],
    '🛶': ['canoe'],
    '⛵': ['sailboat'],
    '🚤': ['speedboat'],
    '🛥️': ['motor', 'boat'],
    '🛳️': ['passenger', 'ship'],
    '⛴️': ['ferry'],
    '🚢': ['ship'],
    'anchor': ['anchor'], // ⚓
    '⚓': ['anchor'],
    '🪝': ['hook'],
    'fuel': ['fuel', 'pump'], // ⛽
    '⛽': ['fuel', 'pump'],
    '🚧': ['construction'],
    'traffic_light': ['traffic', 'light'], // 🚦
    '🚦': ['traffic', 'light'],
    '🚥': ['horizontal', 'traffic', 'light'],
    '🚏': ['bus', 'stop'],
    'map': ['map'], // 🗺️
    '🗺️': ['map'],
    '🗿': ['moai', 'statue'],
    '🗽': ['statue', 'liberty'],
    '🗼': ['tokyo', 'tower'],
    'castle': ['castle'], // 🏰
    '🏰': ['castle'],
    '🏯': ['japanese', 'castle'],
    'stadium': ['stadium'], // 🏟️
    '🏟️': ['stadium'],
    'ferris_wheel': ['ferris', 'wheel'], // 🎡
    '🎡': ['ferris', 'wheel'],
    '🎢': ['roller', 'coaster'],
    '🎠': ['carousel', 'horse'],
    '⛲': ['fountain'],
    '⛱️': ['umbrella', 'ground'],
    'beach': ['beach', 'umbrella'], // 🏖️
    '🏖️': ['beach', 'umbrella'],
    'island': ['island'], // 🏝️
    '🏝️': ['island'],
    'desert': ['desert'], // 🏜️
    '🏜️': ['desert'],
    'volcano': ['volcano'], // 🌋
    '🌋': ['volcano'],
    'mountain': ['mountain'], // ⛰️
    '⛰️': ['mountain'],
    'snow_capped_mountain': ['snow-capped', 'mountain'], // 🏔️
    '🏔️': ['snow-capped', 'mountain'],
    'mt_fuji': ['mount', 'fuji'], // 🗻
    '🗻': ['mount', 'fuji'],
    'camping': ['camping'], // 🏕️
    '🏕️': ['camping'],
    'tent': ['tent'], // ⛺
    '⛺': ['tent'],
    'hut': ['hut'], // 🛖
    '🛖': ['hut'],
    'house': ['house'], // 🏠
    '🏠': ['house'],
    'house_with_garden': ['house', 'garden'], // 🏡
    '🏡': ['house', 'garden'],
    'houses': ['houses'], // 🏘️
    '🏘️': ['houses'],
    'derelict_house': ['derelict', 'house'], // 🏚️
    '🏚️': ['derelict', 'house'],
    'building_construction': ['building', 'construction'], // 🏗️
    '🏗️': ['building', 'construction'],
    'factory': ['factory'], // 🏭
    '🏭': ['factory'],
    'office': ['office', 'building'], // 🏢
    '🏢': ['office', 'building'],
    'department_store': ['department', 'store'], // 🏬
    '🏬': ['department', 'store'],
    'post_office': ['post', 'office'], // 🏣
    '🏣': ['post', 'office'],
    'european_post_office': ['european', 'post', 'office'], // 🏤
    '🏤': ['european', 'post', 'office'],
    'hospital': ['hospital'], // 🏥
    '🏥': ['hospital'],
    'bank': ['bank'], // 🏦
    '🏦': ['bank'],
    'hotel': ['hotel'], // 🏨
    '🏨': ['hotel'],
    'convenience_store': ['convenience', 'store'], // 🏪
    '🏪': ['convenience', 'store'],
    'school': ['school'], // 🏫
    '🏫': ['school'],
    'love_hotel': ['love', 'hotel'], // 🏩
    '🏩': ['love', 'hotel'],
    'wedding': ['wedding'], // 💒
    '💒': ['wedding'],
    'classical_building': ['classical', 'building'], // 🏛️
    '🏛️': ['classical', 'building'],
    'church': ['church'], // ⛪
    '⛪': ['church'],
    'mosque': ['mosque'], // 🕌
    '🕌': ['mosque'],
    'synagogue': ['synagogue'], // 🕍
    '🕍': ['synagogue'],
    'hindu_temple': ['hindu', 'temple'], // 🛕
    '🛕': ['hindu', 'temple'],
    'kaaba': ['kaaba'], // 🕋
    '🕋': ['kaaba'],
    'shinto_shrine': ['shinto', 'shrine'], // ⛩️
    '⛩️': ['shinto', 'shrine'],
    'railway_track': ['railway', 'track'], // 🛤️
    '🛤️': ['railway', 'track'],
    'motorway': ['motorway'], // 🛣️
    '🛣️': ['motorway'],
    'japan': ['map', 'japan'], // 🗾
    '🗾': ['map', 'japan'],
    'moon_ceremony': ['moon', 'viewing', 'ceremony'], // 🎑
    '🎑': ['moon', 'viewing', 'ceremony'],
    'national_park': ['national', 'park'], // 🏞️
    '🏞️': ['national', 'park'],
    'sunrise': ['sunrise'], // 🌅
    '🌅': ['sunrise'],
    'sunrise_over_mountains': ['sunrise', 'mountains'], // 🌄
    '🌄': ['sunrise', 'mountains'],
    'shooting_star': ['shooting', 'star'], // 🌠
    '🌠': ['shooting', 'star'],
    'sparkler': ['sparkler'], // 🎇
    '🎇': ['sparkler'],
    'fireworks': ['fireworks'], // 🎆
    '🎆': ['fireworks'],
    'sunset': ['sunset'], // 🌇
    '🌇': ['sunset'],
    'cityscape': ['cityscape', 'dusk'], // 🌆
    '🌆': ['cityscape', 'dusk'],
    'cityscape_at_night': ['cityscape', 'night'], // 🏙️
    '🏙️': ['cityscape', 'night'],
    'night_with_stars': ['night', 'stars'], // 🌃
    '🌃': ['night', 'stars'],
    'milky_way': ['milky', 'way'], // 🌌
    '🌌': ['milky', 'way'],
    'bridge': ['bridge', 'night'], // 🌉
    '🌉': ['bridge', 'night'],
    'foggy': ['foggy'], // 🌁
    '🌁': ['foggy'],

    // Objects
    '💻': ['laptop', 'computer'],
    '📱': ['mobile', 'phone'],
    '🔨': ['hammer', 'tool'],
    '⚙️': ['gear', 'settings'],
    '💡': ['light', 'bulb', 'idea'],
    '🎉': ['party', 'popper', 'celebration'],
    '🎁': ['wrapped', 'gift', 'present'],
    '🎈': ['balloon'],
    '🔑': ['key', 'password'],
    '🔒': ['lock', 'secure'],

    // Symbols

    '✅': ['check', 'mark', 'button', 'green'],
    '❌': ['cross', 'mark', 'red'],
    '⚠️': ['warning', 'sign'],
    '⛔': ['no', 'entry'],

    // Flags - Generic fallback for flags
    '🏳️': ['white', 'flag', 'surrender'],
    '🏳️‍🌈': ['rainbow', 'flag', 'pride', 'lgbt'],
    '🇺🇸': ['us', 'flag', 'united', 'states', 'america', 'usa'],
    '🇬🇧': ['uk', 'flag', 'united', 'kingdom', 'britain'],

    // Names derived from the Unicode character database so every emoji in the
    // picker has a spoken accessible name and is reachable by search. Hand-written
    // entries above win; these only fill the gap.
    '⛏️': ['pick'],
    '⌚': ['watch'],
    '📲': ['mobile phone with rightwards arrow at left', 'mobile', 'phone', 'rightwards', 'arrow', 'at'],
    '⌨️': ['keyboard'],
    '🖥️': ['desktop computer', 'desktop', 'computer'],
    '🖨️': ['printer'],
    '🖱️': ['three button mouse', 'three', 'button', 'mouse'],
    '🖲️': ['trackball'],
    '🕹️': ['joystick'],
    '🗜️': ['compression'],
    '💽': ['minidisc'],
    '💾': ['floppy disk', 'floppy', 'disk'],
    '💿': ['optical disc', 'optical', 'disc'],
    '📀': ['dvd'],
    '📼': ['videocassette'],
    '📷': ['camera'],
    '📸': ['camera with flash', 'camera', 'flash'],
    '📹': ['video camera', 'video', 'camera'],
    '🎥': ['movie camera', 'movie', 'camera'],
    '📽️': ['film projector', 'film', 'projector'],
    '🎞️': ['film frames', 'film', 'frames'],
    '📞': ['telephone receiver', 'telephone', 'receiver'],
    '☎️': ['black telephone', 'black', 'telephone'],
    '📟': ['pager'],
    '📠': ['fax machine', 'fax', 'machine'],
    '📺': ['television'],
    '📻': ['radio'],
    '🎙️': ['studio microphone', 'studio', 'microphone'],
    '🎚️': ['level slider', 'level', 'slider'],
    '🎛️': ['control knobs', 'control', 'knobs'],
    '🧭': ['compass'],
    '⏱️': ['stopwatch'],
    '⏲️': ['timer clock', 'timer', 'clock'],
    '⏰': ['alarm clock', 'alarm', 'clock'],
    '🕰️': ['mantelpiece clock', 'mantelpiece', 'clock'],
    '⌛': ['hourglass'],
    '⏳': ['hourglass with flowing sand', 'hourglass', 'flowing', 'sand'],
    '📡': ['satellite antenna', 'satellite', 'antenna'],
    '🔋': ['battery'],
    '🔌': ['electric plug', 'electric', 'plug'],
    '🔦': ['electric torch', 'electric', 'torch'],
    '🕯️': ['candle'],
    '🪔': ['diya lamp', 'diya', 'lamp'],
    '🧯': ['fire extinguisher', 'fire', 'extinguisher'],
    '🛢️': ['oil drum', 'oil', 'drum'],
    '💸': ['money with wings', 'money', 'wings'],
    '💵': ['banknote with dollar sign', 'banknote', 'dollar', 'sign'],
    '💴': ['banknote with yen sign', 'banknote', 'yen', 'sign'],
    '💶': ['banknote with euro sign', 'banknote', 'euro', 'sign'],
    '💷': ['banknote with pound sign', 'banknote', 'pound', 'sign'],
    '🪙': ['coin'],
    '💰': ['money bag', 'money', 'bag'],
    '💳': ['credit card', 'credit', 'card'],
    '💎': ['gem stone', 'gem', 'stone'],
    '⚖️': ['scales'],
    '🪜': ['ladder'],
    '🧰': ['toolbox'],
    '🪛': ['screwdriver'],
    '🔧': ['wrench'],
    '⚒️': ['hammer and pick', 'hammer', 'pick'],
    '🛠️': ['hammer and wrench', 'hammer', 'wrench'],
    '🪚': ['carpentry saw', 'carpentry', 'saw'],
    '🔩': ['nut and bolt', 'nut', 'bolt'],
    '🪤': ['mouse trap', 'mouse', 'trap'],
    '🧱': ['brick'],
    '⛓️': ['chains'],
    '🧲': ['magnet'],
    '🔫': ['pistol'],
    '🧨': ['firecracker'],
    '🪓': ['axe'],
    '🗡️': ['dagger knife', 'dagger', 'knife'],
    '⚔️': ['crossed swords', 'crossed', 'swords'],
    '🛡️': ['shield'],
    '🚬': ['smoking symbol', 'smoking', 'symbol'],
    '⚰️': ['coffin'],
    '🪦': ['headstone'],
    '⚱️': ['funeral urn', 'funeral', 'urn'],
    '🔮': ['crystal ball', 'crystal', 'ball'],
    '📿': ['prayer beads', 'prayer', 'beads'],
    '🧿': ['nazar amulet', 'nazar', 'amulet'],
    '💈': ['barber pole', 'barber', 'pole'],
    '⚗️': ['alembic'],
    '🔭': ['telescope'],
    '🔬': ['microscope'],
    '🩹': ['adhesive bandage', 'adhesive', 'bandage'],
    '🩺': ['stethoscope'],
    '💊': ['pill'],
    '💉': ['syringe'],
    '🩸': ['drop of blood', 'drop', 'blood'],
    '🧬': ['dna double helix', 'dna', 'double', 'helix'],
    '🦠': ['microbe'],
    '🧫': ['petri dish', 'petri', 'dish'],
    '🧪': ['test tube', 'test', 'tube'],
    '🌡️': ['thermometer'],
    '🧹': ['broom'],
    '🪠': ['plunger'],
    '🧺': ['basket'],
    '🧻': ['roll of paper', 'roll', 'paper'],
    '🚽': ['toilet'],
    '🚰': ['potable water symbol', 'potable', 'water', 'symbol'],
    '🚿': ['shower'],
    '🛁': ['bathtub'],
    '🛀': ['bath'],
    '🧼': ['bar of soap', 'bar', 'soap'],
    '🪥': ['toothbrush'],
    '🪒': ['razor'],
    '🧽': ['sponge'],
    '🪣': ['bucket'],
    '🧴': ['lotion bottle', 'lotion', 'bottle'],
    '🛎️': ['bellhop bell', 'bellhop', 'bell'],
    '🗝️': ['old key', 'old', 'key'],
    '🚪': ['door'],
    '🪑': ['chair'],
    '🛋️': ['couch and lamp', 'couch', 'lamp'],
    '🛏️': ['bed'],
    '🛌': ['sleeping accommodation', 'sleeping', 'accommodation'],
    '🧸': ['teddy bear', 'teddy', 'bear'],
    '🪆': ['nesting dolls', 'nesting', 'dolls'],
    '🖼️': ['frame with picture', 'frame', 'picture'],
    '🪞': ['mirror'],
    '🪟': ['window'],
    '🛍️': ['shopping bags', 'shopping', 'bags'],
    '🛒': ['shopping trolley', 'shopping', 'trolley'],
    '🎏': ['carp streamer', 'carp', 'streamer'],
    '🎀': ['ribbon'],
    '🪄': ['magic wand', 'magic', 'wand'],
    '🪅': ['pinata'],
    '🎊': ['confetti ball', 'confetti', 'ball'],
    '🎎': ['japanese dolls', 'japanese', 'dolls'],
    '🏮': ['izakaya lantern', 'izakaya', 'lantern'],
    '🎐': ['wind chime', 'wind', 'chime'],
    '🧧': ['red gift envelope', 'red', 'gift', 'envelope'],
    '✉️': ['envelope'],
    '📩': ['envelope with downwards arrow above', 'envelope', 'downwards', 'arrow', 'above'],
    '📨': ['incoming envelope', 'incoming', 'envelope'],
    '📧': ['e-mail symbol', 'e', 'mail', 'symbol'],
    '📥': ['inbox tray', 'inbox', 'tray'],
    '📤': ['outbox tray', 'outbox', 'tray'],
    '📦': ['package'],
    '🏷️': ['label'],
    '📪': ['closed mailbox with lowered flag', 'closed', 'mailbox', 'lowered', 'flag'],
    '📫': ['closed mailbox with raised flag', 'closed', 'mailbox', 'raised', 'flag'],
    '📬': ['open mailbox with raised flag', 'open', 'mailbox', 'raised', 'flag'],
    '📭': ['open mailbox with lowered flag', 'open', 'mailbox', 'lowered', 'flag'],
    '📮': ['postbox'],
    '📯': ['postal horn', 'postal', 'horn'],
    '📜': ['scroll'],
    '📃': ['page with curl', 'page', 'curl'],
    '📄': ['page facing up', 'page', 'facing', 'up'],
    '📑': ['bookmark tabs', 'bookmark', 'tabs'],
    '🧾': ['receipt'],
    '📊': ['bar chart', 'bar', 'chart'],
    '📈': ['chart with upwards trend', 'chart', 'upwards', 'trend'],
    '📉': ['chart with downwards trend', 'chart', 'downwards', 'trend'],
    '🗒️': ['spiral note pad', 'spiral', 'note', 'pad'],
    '🗓️': ['spiral calendar pad', 'spiral', 'calendar', 'pad'],
    '📆': ['tear-off calendar', 'tear', 'off', 'calendar'],
    '📅': ['calendar'],
    '🗑️': ['wastebasket'],
    '📇': ['card index', 'card', 'index'],
    '🗃️': ['card file box', 'card', 'file', 'box'],
    '🗳️': ['ballot box with ballot', 'ballot', 'box'],
    '🗄️': ['file cabinet', 'file', 'cabinet'],
    '📋': ['clipboard'],
    '📁': ['file folder', 'file', 'folder'],
    '📂': ['open file folder', 'open', 'file', 'folder'],
    '🗂️': ['card index dividers', 'card', 'index', 'dividers'],
    '🗞️': ['rolled-up newspaper', 'rolled', 'up', 'newspaper'],
    '📰': ['newspaper'],
    '📓': ['notebook'],
    '📔': ['notebook with decorative cover', 'notebook', 'decorative', 'cover'],
    '📒': ['ledger'],
    '📕': ['closed book', 'closed', 'book'],
    '📗': ['green book', 'green', 'book'],
    '📘': ['blue book', 'blue', 'book'],
    '📙': ['orange book', 'orange', 'book'],
    '📚': ['books'],
    '📖': ['open book', 'open', 'book'],
    '🔖': ['bookmark'],
    '🧷': ['safety pin', 'safety', 'pin'],
    '🔗': ['link symbol', 'link', 'symbol'],
    '📎': ['paperclip'],
    '🖇️': ['linked paperclips', 'linked', 'paperclips'],
    '📐': ['triangular ruler', 'triangular', 'ruler'],
    '📏': ['straight ruler', 'straight', 'ruler'],
    '🧮': ['abacus'],
    '📌': ['pushpin'],
    '📍': ['round pushpin', 'round', 'pushpin'],
    '✂️': ['black scissors', 'black', 'scissors'],
    '🖊️': ['lower left ballpoint pen', 'lower', 'left', 'ballpoint', 'pen'],
    '🖋️': ['lower left fountain pen', 'lower', 'left', 'fountain', 'pen'],
    '✒️': ['black nib', 'black', 'nib'],
    '🖌️': ['lower left paintbrush', 'lower', 'left', 'paintbrush'],
    '🖍️': ['lower left crayon', 'lower', 'left', 'crayon'],
    '📝': ['memo'],
    '✏️': ['pencil'],
    '🔍': ['left-pointing magnifying glass', 'left', 'pointing', 'magnifying', 'glass'],
    '🔎': ['right-pointing magnifying glass', 'right', 'pointing', 'magnifying', 'glass'],
    '🔏': ['lock with ink pen', 'lock', 'ink', 'pen'],
    '🔐': ['closed lock with key', 'closed', 'lock', 'key'],
    '🔓': ['open lock', 'open', 'lock'],
    '☮️': ['peace symbol', 'peace', 'symbol'],
    '✝️': ['latin cross', 'latin', 'cross'],
    '☪️': ['star and crescent', 'star', 'crescent'],
    '🕉️': ['om symbol', 'om', 'symbol'],
    '☸️': ['wheel of dharma', 'wheel', 'dharma'],
    '✡️': ['star of david', 'star', 'david'],
    '🔯': ['six pointed star with middle dot', 'six', 'pointed', 'star', 'middle', 'dot'],
    '🕎': ['menorah with nine branches', 'menorah', 'nine', 'branches'],
    '☯️': ['yin yang', 'yin', 'yang'],
    '☦️': ['orthodox cross', 'orthodox', 'cross'],
    '🛐': ['place of worship', 'place', 'worship'],
    '⛎': ['ophiuchus'],
    '♈': ['aries'],
    '♉': ['taurus'],
    '♊': ['gemini'],
    '♋': ['cancer'],
    '♌': ['leo'],
    '♍': ['virgo'],
    '♎': ['libra'],
    '♏': ['scorpius'],
    '♐': ['sagittarius'],
    '♑': ['capricorn'],
    '♒': ['aquarius'],
    '♓': ['pisces'],
    '🆔': ['squared id', 'squared', 'id'],
    '⚛️': ['atom symbol', 'atom', 'symbol'],
    '🉑': ['circled ideograph accept', 'circled', 'ideograph', 'accept'],
    '☢️': ['radioactive sign', 'radioactive', 'sign'],
    '☣️': ['biohazard sign', 'biohazard', 'sign'],
    '📴': ['mobile phone off', 'mobile', 'phone', 'off'],
    '📳': ['vibration mode', 'vibration', 'mode'],
    '🈶': ['squared cjk unified ideograph-6709', 'squared', 'cjk', 'unified', 'ideograph', '6709'],
    '🈚': ['squared cjk unified ideograph-7121', 'squared', 'cjk', 'unified', 'ideograph', '7121'],
    '🈸': ['squared cjk unified ideograph-7533', 'squared', 'cjk', 'unified', 'ideograph', '7533'],
    '🈺': ['squared cjk unified ideograph-55b6', 'squared', 'cjk', 'unified', 'ideograph', '55b6'],
    '🈷️': ['squared cjk unified ideograph-6708', 'squared', 'cjk', 'unified', 'ideograph', '6708'],
    '✴️': ['eight pointed black star', 'eight', 'pointed', 'black', 'star'],
    '🆚': ['squared vs', 'squared', 'vs'],
    '💮': ['white flower', 'white', 'flower'],
    '🉐': ['circled ideograph advantage', 'circled', 'ideograph', 'advantage'],
    '㊙️': ['circled ideograph secret', 'circled', 'ideograph', 'secret'],
    '㊗️': ['circled ideograph congratulation', 'circled', 'ideograph', 'congratulation'],
    '🈴': ['squared cjk unified ideograph-5408', 'squared', 'cjk', 'unified', 'ideograph', '5408'],
    '🈵': ['squared cjk unified ideograph-6e80', 'squared', 'cjk', 'unified', 'ideograph', '6e80'],
    '🈹': ['squared cjk unified ideograph-5272', 'squared', 'cjk', 'unified', 'ideograph', '5272'],
    '🈲': ['squared cjk unified ideograph-7981', 'squared', 'cjk', 'unified', 'ideograph', '7981'],
    '🅰️': ['negative squared latin capital letter a', 'negative', 'squared', 'latin', 'capital', 'letter'],
    '🅱️': ['negative squared latin capital letter b', 'negative', 'squared', 'latin', 'capital', 'letter'],
    '🆎': ['negative squared ab', 'negative', 'squared', 'ab'],
    '🆑': ['squared cl', 'squared', 'cl'],
    '🅾️': ['negative squared latin capital letter o', 'negative', 'squared', 'latin', 'capital', 'letter'],
    '🆘': ['squared sos', 'squared', 'sos'],
    '⭕': ['heavy large circle', 'heavy', 'large', 'circle'],
    '🛑': ['octagonal sign', 'octagonal', 'sign'],
    '📛': ['name badge', 'name', 'badge'],
    '🚫': ['no entry sign', 'no', 'entry', 'sign'],
    '♨️': ['hot springs', 'hot', 'springs'],
    '🚷': ['no pedestrians', 'no', 'pedestrians'],
    '🚯': ['do not litter symbol', 'do', 'not', 'litter', 'symbol'],
    '🚳': ['no bicycles', 'no', 'bicycles'],
    '🚱': ['non-potable water symbol', 'non', 'potable', 'water', 'symbol'],
    '🔞': ['no one under eighteen symbol', 'no', 'one', 'under', 'eighteen', 'symbol'],
    '📵': ['no mobile phones', 'no', 'mobile', 'phones'],
    '🚭': ['no smoking symbol', 'no', 'smoking', 'symbol'],
    '❗': ['heavy exclamation mark symbol', 'heavy', 'exclamation', 'mark', 'symbol'],
    '❕': ['white exclamation mark ornament', 'white', 'exclamation', 'mark', 'ornament'],
    '❓': ['black question mark ornament', 'black', 'question', 'mark', 'ornament'],
    '❔': ['white question mark ornament', 'white', 'question', 'mark', 'ornament'],
    '‼️': ['double exclamation mark', 'double', 'exclamation', 'mark'],
    '⁉️': ['exclamation question mark', 'exclamation', 'question', 'mark'],
    '🔅': ['low brightness symbol', 'low', 'brightness', 'symbol'],
    '🔆': ['high brightness symbol', 'high', 'brightness', 'symbol'],
    '〽️': ['part alternation mark', 'part', 'alternation', 'mark'],
    '🚸': ['children crossing', 'children', 'crossing'],
    '🔱': ['trident emblem', 'trident', 'emblem'],
    '⚜️': ['fleur-de-lis', 'fleur', 'de', 'lis'],
    '🔰': ['japanese symbol for beginner', 'japanese', 'symbol', 'for', 'beginner'],
    '♻️': ['black universal recycling symbol', 'black', 'universal', 'recycling', 'symbol'],
    '🈯': ['squared cjk unified ideograph-6307', 'squared', 'cjk', 'unified', 'ideograph', '6307'],
    '💹': ['chart with upwards trend and yen sign', 'chart', 'upwards', 'trend', 'yen', 'sign'],
    '❇️': ['sparkle'],
    '✳️': ['eight spoked asterisk', 'eight', 'spoked', 'asterisk'],
    '❎': ['negative squared cross mark', 'negative', 'squared', 'cross', 'mark'],
    '🌐': ['globe with meridians', 'globe', 'meridians'],
    '💠': ['diamond shape with a dot inside', 'diamond', 'shape', 'dot', 'inside'],
    'Ⓜ️': ['circled latin capital letter m', 'circled', 'latin', 'capital', 'letter', 'm'],
    '🌀': ['cyclone'],
    '🏧': ['automated teller machine', 'automated', 'teller', 'machine'],
    '🚾': ['water closet', 'water', 'closet'],
    '♿': ['wheelchair symbol', 'wheelchair', 'symbol'],
    '🅿️': ['negative squared latin capital letter p', 'negative', 'squared', 'latin', 'capital', 'letter'],
    '🛗': ['elevator'],
    '🈳': ['squared cjk unified ideograph-7a7a', 'squared', 'cjk', 'unified', 'ideograph', '7a7a'],
    '🈂️': ['squared katakana sa', 'squared', 'katakana', 'sa'],
    '🛂': ['passport control', 'passport', 'control'],
    '🛃': ['customs'],
    '🛄': ['baggage claim', 'baggage', 'claim'],
    '🛅': ['left luggage', 'left', 'luggage'],
    '🚹': ['mens symbol', 'mens', 'symbol'],
    '🚺': ['womens symbol', 'womens', 'symbol'],
    '🚼': ['baby symbol', 'baby', 'symbol'],
    '⚧️': ['male with stroke and male and female sign', 'male', 'stroke', 'female', 'sign'],
    '🚻': ['restroom'],
    '🚮': ['put litter in its place symbol', 'put', 'litter', 'in', 'its', 'place'],
    '🎦': ['cinema'],
    '📶': ['antenna with bars', 'antenna', 'bars'],
    '🈁': ['squared katakana koko', 'squared', 'katakana', 'koko'],
    '🔣': ['input symbol for symbols', 'input', 'symbol', 'for', 'symbols'],
    '🔤': ['input symbol for latin letters', 'input', 'symbol', 'for', 'latin', 'letters'],
    '🔡': ['input symbol for latin small letters', 'input', 'symbol', 'for', 'latin', 'small'],
    '🔠': ['input symbol for latin capital letters', 'input', 'symbol', 'for', 'latin', 'capital'],
    '🆖': ['squared ng', 'squared', 'ng'],
    '🆗': ['squared ok', 'squared', 'ok'],
    '🆙': ['squared up with exclamation mark', 'squared', 'up', 'exclamation', 'mark'],
    '🆒': ['squared cool', 'squared', 'cool'],
    '🆕': ['squared new', 'squared', 'new'],
    '🆓': ['squared free', 'squared', 'free'],
    '0️⃣': ['digit zero combining enclosing keycap', 'digit', 'zero', 'combining', 'enclosing', 'keycap'],
    '1️⃣': ['digit one combining enclosing keycap', 'digit', 'one', 'combining', 'enclosing', 'keycap'],
    '2️⃣': ['digit two combining enclosing keycap', 'digit', 'two', 'combining', 'enclosing', 'keycap'],
    '3️⃣': ['digit three combining enclosing keycap', 'digit', 'three', 'combining', 'enclosing', 'keycap'],
    '4️⃣': ['digit four combining enclosing keycap', 'digit', 'four', 'combining', 'enclosing', 'keycap'],
    '5️⃣': ['digit five combining enclosing keycap', 'digit', 'five', 'combining', 'enclosing', 'keycap'],
    '6️⃣': ['digit six combining enclosing keycap', 'digit', 'six', 'combining', 'enclosing', 'keycap'],
    '7️⃣': ['digit seven combining enclosing keycap', 'digit', 'seven', 'combining', 'enclosing', 'keycap'],
    '8️⃣': ['digit eight combining enclosing keycap', 'digit', 'eight', 'combining', 'enclosing', 'keycap'],
    '9️⃣': ['digit nine combining enclosing keycap', 'digit', 'nine', 'combining', 'enclosing', 'keycap'],
    '🔟': ['keycap ten', 'keycap', 'ten'],
    '🔢': ['input symbol for numbers', 'input', 'symbol', 'for', 'numbers'],
    '#️⃣': ['number sign combining enclosing keycap', 'number', 'sign', 'combining', 'enclosing', 'keycap'],
    '*️⃣': ['asterisk combining enclosing keycap', 'asterisk', 'combining', 'enclosing', 'keycap'],
    '⏏️': ['eject symbol', 'eject', 'symbol'],
    '▶️': ['black right-pointing triangle', 'black', 'right', 'pointing', 'triangle'],
    '⏸️': ['double vertical bar', 'double', 'vertical', 'bar'],
    '⏯️': ['black right-pointing triangle with double vertical bar', 'black', 'right', 'pointing', 'triangle', 'double'],
    '⏹️': ['black square for stop', 'black', 'square', 'for', 'stop'],
    '⏺️': ['black circle for record', 'black', 'circle', 'for', 'record'],
    '⏭️': ['black right-pointing double triangle with vertical bar', 'black', 'right', 'pointing', 'double', 'triangle'],
    '⏮️': ['black left-pointing double triangle with vertical bar', 'black', 'left', 'pointing', 'double', 'triangle'],
    '⏩': ['black right-pointing double triangle', 'black', 'right', 'pointing', 'double', 'triangle'],
    '⏪': ['black left-pointing double triangle', 'black', 'left', 'pointing', 'double', 'triangle'],
    '⏫': ['black up-pointing double triangle', 'black', 'up', 'pointing', 'double', 'triangle'],
    '⏬': ['black down-pointing double triangle', 'black', 'down', 'pointing', 'double', 'triangle'],
    '◀️': ['black left-pointing triangle', 'black', 'left', 'pointing', 'triangle'],
    '🔼': ['up-pointing small red triangle', 'up', 'pointing', 'small', 'red', 'triangle'],
    '🔽': ['down-pointing small red triangle', 'down', 'pointing', 'small', 'red', 'triangle'],
    '➡️': ['black rightwards arrow', 'black', 'rightwards', 'arrow'],
    '⬅️': ['leftwards black arrow', 'leftwards', 'black', 'arrow'],
    '⬆️': ['upwards black arrow', 'upwards', 'black', 'arrow'],
    '⬇️': ['downwards black arrow', 'downwards', 'black', 'arrow'],
    '↗️': ['north east arrow', 'north', 'east', 'arrow'],
    '↘️': ['south east arrow', 'south', 'east', 'arrow'],
    '↙️': ['south west arrow', 'south', 'west', 'arrow'],
    '↖️': ['north west arrow', 'north', 'west', 'arrow'],
    '↕️': ['up down arrow', 'up', 'down', 'arrow'],
    '↔️': ['left right arrow', 'left', 'right', 'arrow'],
    '↪️': ['rightwards arrow with hook', 'rightwards', 'arrow', 'hook'],
    '↩️': ['leftwards arrow with hook', 'leftwards', 'arrow', 'hook'],
    '⤴️': ['arrow pointing rightwards then curving upwards', 'arrow', 'pointing', 'rightwards', 'then', 'curving'],
    '⤵️': ['arrow pointing rightwards then curving downwards', 'arrow', 'pointing', 'rightwards', 'then', 'curving'],
    '🔀': ['twisted rightwards arrows', 'twisted', 'rightwards', 'arrows'],
    '🔁': ['clockwise rightwards and leftwards open circle arrows', 'clockwise', 'rightwards', 'leftwards', 'open', 'circle'],
    '🔂': ['clockwise rightwards and leftwards open circle arrows with circled one overlay', 'clockwise', 'rightwards', 'leftwards', 'open', 'circle'],
    '🔄': ['anticlockwise downwards and upwards open circle arrows', 'anticlockwise', 'downwards', 'upwards', 'open', 'circle'],
    '🔃': ['clockwise downwards and upwards open circle arrows', 'clockwise', 'downwards', 'upwards', 'open', 'circle'],
    '🎵': ['musical note', 'musical', 'note'],
    '🎶': ['multiple musical notes', 'multiple', 'musical', 'notes'],
    '➕': ['heavy plus sign', 'heavy', 'plus', 'sign'],
    '➖': ['heavy minus sign', 'heavy', 'minus', 'sign'],
    '➗': ['heavy division sign', 'heavy', 'division', 'sign'],
    '✖️': ['heavy multiplication x', 'heavy', 'multiplication', 'x'],
    '🟰': ['heavy equals sign', 'heavy', 'equals', 'sign'],
    '♾️': ['permanent paper sign', 'permanent', 'paper', 'sign'],
    '💲': ['heavy dollar sign', 'heavy', 'dollar', 'sign'],
    '💱': ['currency exchange', 'currency', 'exchange'],
    '™️': ['trade mark sign', 'trade', 'mark', 'sign'],
    '©️': ['copyright sign', 'copyright', 'sign'],
    '®️': ['registered sign', 'registered', 'sign'],
    '〰️': ['wavy dash', 'wavy', 'dash'],
    '➰': ['curly loop', 'curly', 'loop'],
    '➿': ['double curly loop', 'double', 'curly', 'loop'],
    '🔚': ['end with leftwards arrow above', 'end', 'leftwards', 'arrow', 'above'],
    '🔙': ['back with leftwards arrow above', 'back', 'leftwards', 'arrow', 'above'],
    '🔛': ['on with exclamation mark with left right arrow above', 'on', 'exclamation', 'mark', 'left', 'right'],
    '🔝': ['top with upwards arrow above', 'top', 'upwards', 'arrow', 'above'],
    '🔜': ['soon with rightwards arrow above', 'soon', 'rightwards', 'arrow', 'above'],
    '✔️': ['heavy check mark', 'heavy', 'check', 'mark'],
    '☑️': ['ballot box with check', 'ballot', 'box', 'check'],
    '🔘': ['radio button', 'radio', 'button'],
    '🔴': ['large red circle', 'large', 'red', 'circle'],
    '🟠': ['large orange circle', 'large', 'orange', 'circle'],
    '🟡': ['large yellow circle', 'large', 'yellow', 'circle'],
    '🟢': ['large green circle', 'large', 'green', 'circle'],
    '🔵': ['large blue circle', 'large', 'blue', 'circle'],
    '🟣': ['large purple circle', 'large', 'purple', 'circle'],
    '⚫': ['medium black circle', 'medium', 'black', 'circle'],
    '⚪': ['medium white circle', 'medium', 'white', 'circle'],
    '🟤': ['large brown circle', 'large', 'brown', 'circle'],
    '🔺': ['up-pointing red triangle', 'up', 'pointing', 'red', 'triangle'],
    '🔻': ['down-pointing red triangle', 'down', 'pointing', 'red', 'triangle'],
    '🔸': ['small orange diamond', 'small', 'orange', 'diamond'],
    '🔹': ['small blue diamond', 'small', 'blue', 'diamond'],
    '🔶': ['large orange diamond', 'large', 'orange', 'diamond'],
    '🔷': ['large blue diamond', 'large', 'blue', 'diamond'],
    '🔳': ['white square button', 'white', 'square', 'button'],
    '🔲': ['black square button', 'black', 'square', 'button'],
    '▪️': ['black small square', 'black', 'small', 'square'],
    '▫️': ['white small square', 'white', 'small', 'square'],
    '◾': ['black medium small square', 'black', 'medium', 'small', 'square'],
    '◽': ['white medium small square', 'white', 'medium', 'small', 'square'],
    '◼️': ['black medium square', 'black', 'medium', 'square'],
    '◻️': ['white medium square', 'white', 'medium', 'square'],
    '🟥': ['large red square', 'large', 'red', 'square'],
    '🟧': ['large orange square', 'large', 'orange', 'square'],
    '🟨': ['large yellow square', 'large', 'yellow', 'square'],
    '🟩': ['large green square', 'large', 'green', 'square'],
    '🟦': ['large blue square', 'large', 'blue', 'square'],
    '🟪': ['large purple square', 'large', 'purple', 'square'],
    '⬛': ['black large square', 'black', 'large', 'square'],
    '⬜': ['white large square', 'white', 'large', 'square'],
    '🟫': ['large brown square', 'large', 'brown', 'square'],
    '🔈': ['speaker'],
    '🔇': ['speaker with cancellation stroke', 'speaker', 'cancellation', 'stroke'],
    '🔉': ['speaker with one sound wave', 'speaker', 'one', 'sound', 'wave'],
    '🔊': ['speaker with three sound waves', 'speaker', 'three', 'sound', 'waves'],
    '🔔': ['bell'],
    '🔕': ['bell with cancellation stroke', 'bell', 'cancellation', 'stroke'],
    '📣': ['cheering megaphone', 'cheering', 'megaphone'],
    '📢': ['public address loudspeaker', 'public', 'address', 'loudspeaker'],
    '♠️': ['black spade suit', 'black', 'spade', 'suit'],
    '♣️': ['black club suit', 'black', 'club', 'suit'],
    '♥️': ['black heart suit', 'black', 'heart', 'suit'],
    '♦️': ['black diamond suit', 'black', 'diamond', 'suit'],
    '🃏': ['playing card black joker', 'playing', 'card', 'black', 'joker'],
    '🎴': ['flower playing cards', 'flower', 'playing', 'cards'],
    '🀄': ['mahjong tile red dragon', 'mahjong', 'tile', 'red', 'dragon'],
    '🕐': ['clock face one oclock', 'clock', 'face', 'one', 'oclock'],
    '🕑': ['clock face two oclock', 'clock', 'face', 'two', 'oclock'],
    '🕒': ['clock face three oclock', 'clock', 'face', 'three', 'oclock'],
    '🕓': ['clock face four oclock', 'clock', 'face', 'four', 'oclock'],
    '🕔': ['clock face five oclock', 'clock', 'face', 'five', 'oclock'],
    '🕕': ['clock face six oclock', 'clock', 'face', 'six', 'oclock'],
    '🕖': ['clock face seven oclock', 'clock', 'face', 'seven', 'oclock'],
    '🕗': ['clock face eight oclock', 'clock', 'face', 'eight', 'oclock'],
    '🕘': ['clock face nine oclock', 'clock', 'face', 'nine', 'oclock'],
    '🕙': ['clock face ten oclock', 'clock', 'face', 'ten', 'oclock'],
    '🕚': ['clock face eleven oclock', 'clock', 'face', 'eleven', 'oclock'],
    '🕛': ['clock face twelve oclock', 'clock', 'face', 'twelve', 'oclock'],
    '🕜': ['clock face one-thirty', 'clock', 'face', 'one', 'thirty'],
    '🕝': ['clock face two-thirty', 'clock', 'face', 'two', 'thirty'],
    '🕞': ['clock face three-thirty', 'clock', 'face', 'three', 'thirty'],
    '🕟': ['clock face four-thirty', 'clock', 'face', 'four', 'thirty'],
    '🕠': ['clock face five-thirty', 'clock', 'face', 'five', 'thirty'],
    '🕡': ['clock face six-thirty', 'clock', 'face', 'six', 'thirty'],
    '🕢': ['clock face seven-thirty', 'clock', 'face', 'seven', 'thirty'],
    '🕣': ['clock face eight-thirty', 'clock', 'face', 'eight', 'thirty'],
    '🕤': ['clock face nine-thirty', 'clock', 'face', 'nine', 'thirty'],
    '🕥': ['clock face ten-thirty', 'clock', 'face', 'ten', 'thirty'],
    '🕦': ['clock face eleven-thirty', 'clock', 'face', 'eleven', 'thirty'],
    '🕧': ['clock face twelve-thirty', 'clock', 'face', 'twelve', 'thirty'],
    '🏴': ['waving black flag', 'waving', 'black', 'flag'],
    '🏴‍☠️': ['waving black flag skull and crossbones', 'waving', 'black', 'flag', 'skull', 'crossbones'],
    '🏁': ['chequered flag', 'chequered', 'flag'],
    '🚩': ['triangular flag on post', 'triangular', 'flag', 'on', 'post'],
    '🎌': ['crossed flags', 'crossed', 'flags'],
    '🏳️‍⚧️': ['waving white flag male with stroke and male and female sign', 'waving', 'white', 'flag', 'male', 'stroke'],
    '🇺🇳': ['flag un', 'flag', 'un'],
    '🇦🇫': ['flag af', 'flag', 'af'],
    '🇦🇱': ['flag al', 'flag', 'al'],
    '🇩🇿': ['flag dz', 'flag', 'dz'],
    '🇦🇸': ['flag as', 'flag', 'as'],
    '🇦🇩': ['flag ad', 'flag', 'ad'],
    '🇦🇴': ['flag ao', 'flag', 'ao'],
    '🇦🇮': ['flag ai', 'flag', 'ai'],
    '🇦🇶': ['flag aq', 'flag', 'aq'],
    '🇦🇬': ['flag ag', 'flag', 'ag'],
    '🇦🇷': ['flag ar', 'flag', 'ar'],
    '🇦🇲': ['flag am', 'flag', 'am'],
    '🇦🇼': ['flag aw', 'flag', 'aw'],
    '🇦🇺': ['flag au', 'flag', 'au'],
    '🇦🇹': ['flag at', 'flag', 'at'],
    '🇦🇿': ['flag az', 'flag', 'az'],
    '🇧🇸': ['flag bs', 'flag', 'bs'],
    '🇧🇭': ['flag bh', 'flag', 'bh'],
    '🇧🇩': ['flag bd', 'flag', 'bd'],
    '🇧🇧': ['flag bb', 'flag', 'bb'],
    '🇧🇾': ['flag by', 'flag', 'by'],
    '🇧🇪': ['flag be', 'flag', 'be'],
    '🇧🇿': ['flag bz', 'flag', 'bz'],
    '🇧🇯': ['flag bj', 'flag', 'bj'],
    '🇧🇲': ['flag bm', 'flag', 'bm'],
    '🇧🇹': ['flag bt', 'flag', 'bt'],
    '🇧🇴': ['flag bo', 'flag', 'bo'],
    '🇧🇦': ['flag ba', 'flag', 'ba'],
    '🇧🇼': ['flag bw', 'flag', 'bw'],
    '🇧🇷': ['flag br', 'flag', 'br'],
    '🇻🇬': ['flag vg', 'flag', 'vg'],
    '🇧🇳': ['flag bn', 'flag', 'bn'],
    '🇧🇬': ['flag bg', 'flag', 'bg'],
    '🇧🇫': ['flag bf', 'flag', 'bf'],
    '🇧🇮': ['flag bi', 'flag', 'bi'],
    '🇰🇭': ['flag kh', 'flag', 'kh'],
    '🇨🇲': ['flag cm', 'flag', 'cm'],
    '🇨🇦': ['flag ca', 'flag', 'ca'],
    '🇮🇨': ['flag ic', 'flag', 'ic'],
    '🇨🇻': ['flag cv', 'flag', 'cv'],
    '🇧🇶': ['flag bq', 'flag', 'bq'],
    '🇰🇾': ['flag ky', 'flag', 'ky'],
    '🇨🇫': ['flag cf', 'flag', 'cf'],
    '🇹🇩': ['flag td', 'flag', 'td'],
    '🇨🇱': ['flag cl', 'flag', 'cl'],
    '🇨🇳': ['flag cn', 'flag', 'cn'],
    '🇨🇽': ['flag cx', 'flag', 'cx'],
    '🇨🇨': ['flag cc', 'flag', 'cc'],
    '🇨🇴': ['flag co', 'flag', 'co'],
    '🇰🇲': ['flag km', 'flag', 'km'],
    '🇨🇬': ['flag cg', 'flag', 'cg'],
    '🇨🇩': ['flag cd', 'flag', 'cd'],
    '🇨🇰': ['flag ck', 'flag', 'ck'],
    '🇨🇷': ['flag cr', 'flag', 'cr'],
    '🇨🇮': ['flag ci', 'flag', 'ci'],
    '🇭🇷': ['flag hr', 'flag', 'hr'],
    '🇨🇺': ['flag cu', 'flag', 'cu'],
    '🇨🇼': ['flag cw', 'flag', 'cw'],
    '🇨🇾': ['flag cy', 'flag', 'cy'],
    '🇨🇿': ['flag cz', 'flag', 'cz'],
    '🇩🇰': ['flag dk', 'flag', 'dk'],
    '🇩🇯': ['flag dj', 'flag', 'dj'],
    '🇩🇲': ['flag dm', 'flag', 'dm'],
    '🇩🇴': ['flag do', 'flag', 'do'],
    '🇪🇨': ['flag ec', 'flag', 'ec'],
    '🇪🇬': ['flag eg', 'flag', 'eg'],
    '🇸🇻': ['flag sv', 'flag', 'sv'],
    '🇬🇶': ['flag gq', 'flag', 'gq'],
    '🇪🇷': ['flag er', 'flag', 'er'],
    '🇪🇪': ['flag ee', 'flag', 'ee'],
    '🇸🇿': ['flag sz', 'flag', 'sz'],
    '🇪🇹': ['flag et', 'flag', 'et'],
    '🇪🇺': ['flag eu', 'flag', 'eu'],
    '🇫🇰': ['flag fk', 'flag', 'fk'],
    '🇫🇴': ['flag fo', 'flag', 'fo'],
    '🇫🇯': ['flag fj', 'flag', 'fj'],
    '🇫🇮': ['flag fi', 'flag', 'fi'],
    '🇫🇷': ['flag fr', 'flag', 'fr'],
    '🇬🇫': ['flag gf', 'flag', 'gf'],
    '🇵🇫': ['flag pf', 'flag', 'pf'],
    '🇹🇫': ['flag tf', 'flag', 'tf'],
    '🇬🇦': ['flag ga', 'flag', 'ga'],
    '🇬🇲': ['flag gm', 'flag', 'gm'],
    '🇬🇪': ['flag ge', 'flag', 'ge'],
    '🇩🇪': ['flag de', 'flag', 'de'],
    '🇬🇭': ['flag gh', 'flag', 'gh'],
    '🇬🇮': ['flag gi', 'flag', 'gi'],
    '🇬🇷': ['flag gr', 'flag', 'gr'],
    '🇬🇱': ['flag gl', 'flag', 'gl'],
    '🇬🇩': ['flag gd', 'flag', 'gd'],
    '🇬🇵': ['flag gp', 'flag', 'gp'],
    '🇬🇺': ['flag gu', 'flag', 'gu'],
    '🇬🇹': ['flag gt', 'flag', 'gt'],
    '🇬🇬': ['flag gg', 'flag', 'gg'],
    '🇬🇳': ['flag gn', 'flag', 'gn'],
    '🇬🇼': ['flag gw', 'flag', 'gw'],
    '🇬🇾': ['flag gy', 'flag', 'gy'],
    '🇭🇹': ['flag ht', 'flag', 'ht'],
    '🇭🇳': ['flag hn', 'flag', 'hn'],
    '🇭🇰': ['flag hk', 'flag', 'hk'],
    '🇭🇺': ['flag hu', 'flag', 'hu'],
    '🇮🇸': ['flag is', 'flag', 'is'],
    '🇮🇳': ['flag in', 'flag', 'in'],
    '🇮🇩': ['flag id', 'flag', 'id'],
    '🇮🇷': ['flag ir', 'flag', 'ir'],
    '🇮🇶': ['flag iq', 'flag', 'iq'],
    '🇮🇪': ['flag ie', 'flag', 'ie'],
    '🇮🇲': ['flag im', 'flag', 'im'],
    '🇮🇱': ['flag il', 'flag', 'il'],
    '🇮🇹': ['flag it', 'flag', 'it'],
    '🇯🇲': ['flag jm', 'flag', 'jm'],
    '🇯🇵': ['flag jp', 'flag', 'jp'],
    '🇯🇪': ['flag je', 'flag', 'je'],
    '🇯🇴': ['flag jo', 'flag', 'jo'],
    '🇰🇿': ['flag kz', 'flag', 'kz'],
    '🇰🇪': ['flag ke', 'flag', 'ke'],
    '🇰🇮': ['flag ki', 'flag', 'ki'],
    '🇽🇰': ['flag xk', 'flag', 'xk'],
    '🇰🇼': ['flag kw', 'flag', 'kw'],
    '🇰🇬': ['flag kg', 'flag', 'kg'],
    '🇱🇦': ['flag la', 'flag', 'la'],
    '🇱🇻': ['flag lv', 'flag', 'lv'],
    '🇱🇧': ['flag lb', 'flag', 'lb'],
    '🇱🇸': ['flag ls', 'flag', 'ls'],
    '🇱🇷': ['flag lr', 'flag', 'lr'],
    '🇱🇾': ['flag ly', 'flag', 'ly'],
    '🇱🇮': ['flag li', 'flag', 'li'],
    '🇱🇹': ['flag lt', 'flag', 'lt'],
    '🇱🇺': ['flag lu', 'flag', 'lu'],
    '🇲🇴': ['flag mo', 'flag', 'mo'],
    '🇲🇬': ['flag mg', 'flag', 'mg'],
    '🇲🇼': ['flag mw', 'flag', 'mw'],
    '🇲🇾': ['flag my', 'flag', 'my'],
    '🇲🇻': ['flag mv', 'flag', 'mv'],
    '🇲🇱': ['flag ml', 'flag', 'ml'],
    '🇲🇹': ['flag mt', 'flag', 'mt'],
    '🇲🇭': ['flag mh', 'flag', 'mh'],
    '🇲🇶': ['flag mq', 'flag', 'mq'],
    '🇲🇷': ['flag mr', 'flag', 'mr'],
    '🇲🇺': ['flag mu', 'flag', 'mu'],
    '🇾🇹': ['flag yt', 'flag', 'yt'],
    '🇲🇽': ['flag mx', 'flag', 'mx'],
    '🇫🇲': ['flag fm', 'flag', 'fm'],
    '🇲🇩': ['flag md', 'flag', 'md'],
    '🇲🇨': ['flag mc', 'flag', 'mc'],
    '🇲🇳': ['flag mn', 'flag', 'mn'],
    '🇲🇪': ['flag me', 'flag', 'me'],
    '🇲🇸': ['flag ms', 'flag', 'ms'],
    '🇲🇦': ['flag ma', 'flag', 'ma'],
    '🇲🇿': ['flag mz', 'flag', 'mz'],
    '🇲🇲': ['flag mm', 'flag', 'mm'],
    '🇳🇦': ['flag na', 'flag', 'na'],
    '🇳🇷': ['flag nr', 'flag', 'nr'],
    '🇳🇵': ['flag np', 'flag', 'np'],
    '🇳🇱': ['flag nl', 'flag', 'nl'],
    '🇳🇨': ['flag nc', 'flag', 'nc'],
    '🇳🇿': ['flag nz', 'flag', 'nz'],
    '🇳🇮': ['flag ni', 'flag', 'ni'],
    '🇳🇪': ['flag ne', 'flag', 'ne'],
    '🇳🇬': ['flag ng', 'flag', 'ng'],
    '🇳🇺': ['flag nu', 'flag', 'nu'],
    '🇳🇫': ['flag nf', 'flag', 'nf'],
    '🇰🇵': ['flag kp', 'flag', 'kp'],
    '🇲🇰': ['flag mk', 'flag', 'mk'],
    '🇲🇵': ['flag mp', 'flag', 'mp'],
    '🇳🇴': ['flag no', 'flag', 'no'],
    '🇴🇲': ['flag om', 'flag', 'om'],
    '🇵🇰': ['flag pk', 'flag', 'pk'],
    '🇵🇼': ['flag pw', 'flag', 'pw'],
    '🇵🇸': ['flag ps', 'flag', 'ps'],
    '🇵🇦': ['flag pa', 'flag', 'pa'],
    '🇵🇬': ['flag pg', 'flag', 'pg'],
    '🇵🇾': ['flag py', 'flag', 'py'],
    '🇵🇪': ['flag pe', 'flag', 'pe'],
    '🇵🇭': ['flag ph', 'flag', 'ph'],
    '🇵🇳': ['flag pn', 'flag', 'pn'],
    '🇵🇱': ['flag pl', 'flag', 'pl'],
    '🇵🇹': ['flag pt', 'flag', 'pt'],
    '🇵🇷': ['flag pr', 'flag', 'pr'],
    '🇶🇦': ['flag qa', 'flag', 'qa'],
    '🇷🇪': ['flag re', 'flag', 're'],
    '🇷🇴': ['flag ro', 'flag', 'ro'],
    '🇷🇺': ['flag ru', 'flag', 'ru'],
    '🇷🇼': ['flag rw', 'flag', 'rw'],
    '🇼🇸': ['flag ws', 'flag', 'ws'],
    '🇸🇲': ['flag sm', 'flag', 'sm'],
    '🇸🇹': ['flag st', 'flag', 'st'],
    '🇸🇦': ['flag sa', 'flag', 'sa'],
    '🇸🇳': ['flag sn', 'flag', 'sn'],
    '🇷🇸': ['flag rs', 'flag', 'rs'],
    '🇸🇨': ['flag sc', 'flag', 'sc'],
    '🇸🇱': ['flag sl', 'flag', 'sl'],
    '🇸🇬': ['flag sg', 'flag', 'sg'],
    '🇸🇽': ['flag sx', 'flag', 'sx'],
    '🇸🇰': ['flag sk', 'flag', 'sk'],
    '🇸🇮': ['flag si', 'flag', 'si'],
    '🇬🇸': ['flag gs', 'flag', 'gs'],
    '🇸🇧': ['flag sb', 'flag', 'sb'],
    '🇸🇴': ['flag so', 'flag', 'so'],
    '🇿🇦': ['flag za', 'flag', 'za'],
    '🇰🇷': ['flag kr', 'flag', 'kr'],
    '🇸🇸': ['flag ss', 'flag', 'ss'],
    '🇪🇸': ['flag es', 'flag', 'es'],
    '🇱🇰': ['flag lk', 'flag', 'lk'],
    '🇧🇱': ['flag bl', 'flag', 'bl'],
    '🇸🇭': ['flag sh', 'flag', 'sh'],
    '🇰🇳': ['flag kn', 'flag', 'kn'],
    '🇱🇨': ['flag lc', 'flag', 'lc'],
    '🇵🇲': ['flag pm', 'flag', 'pm'],
    '🇻🇨': ['flag vc', 'flag', 'vc'],
    '🇸🇩': ['flag sd', 'flag', 'sd'],
    '🇸🇷': ['flag sr', 'flag', 'sr'],
    '🇸🇪': ['flag se', 'flag', 'se'],
    '🇨🇭': ['flag ch', 'flag', 'ch'],
    '🇸🇾': ['flag sy', 'flag', 'sy'],
    '🇹🇼': ['flag tw', 'flag', 'tw'],
    '🇹🇯': ['flag tj', 'flag', 'tj'],
    '🇹🇿': ['flag tz', 'flag', 'tz'],
    '🇹🇭': ['flag th', 'flag', 'th'],
    '🇹🇱': ['flag tl', 'flag', 'tl'],
    '🇹🇬': ['flag tg', 'flag', 'tg'],
    '🇹🇰': ['flag tk', 'flag', 'tk'],
    '🇹🇴': ['flag to', 'flag', 'to'],
    '🇹🇹': ['flag tt', 'flag', 'tt'],
    '🇹🇳': ['flag tn', 'flag', 'tn'],
    '🇹🇷': ['flag tr', 'flag', 'tr'],
    '🇹🇲': ['flag tm', 'flag', 'tm'],
    '🇹🇨': ['flag tc', 'flag', 'tc'],
    '🇹🇻': ['flag tv', 'flag', 'tv'],
    '🇻🇮': ['flag vi', 'flag', 'vi'],
    '🇺🇬': ['flag ug', 'flag', 'ug'],
    '🇺🇦': ['flag ua', 'flag', 'ua'],
    '🇦🇪': ['flag ae', 'flag', 'ae'],
    '🏴󠁧󠁢󠁥󠁮󠁧󠁿': ['flag gbeng', 'flag', 'gbeng'],
    '🏴󠁧󠁢󠁳󠁣󠁴󠁿': ['flag gbsct', 'flag', 'gbsct'],
    '🏴󠁧󠁢󠁷󠁬󠁳󠁿': ['flag gbwls', 'flag', 'gbwls'],
    '🇺🇾': ['flag uy', 'flag', 'uy'],
    '🇺🇿': ['flag uz', 'flag', 'uz'],
    '🇻🇺': ['flag vu', 'flag', 'vu'],
    '🇻🇦': ['flag va', 'flag', 'va'],
    '🇻🇪': ['flag ve', 'flag', 've'],
    '🇻🇳': ['flag vn', 'flag', 'vn'],
    '🇼🇫': ['flag wf', 'flag', 'wf'],
    '🇪🇭': ['flag eh', 'flag', 'eh'],
    '🇾🇪': ['flag ye', 'flag', 'ye'],
    '🇿🇲': ['flag zm', 'flag', 'zm'],
    '🇿🇼': ['flag zw', 'flag', 'zw'],
};
