export const EMOJI_DATA: Record<string, string[]> = {
    // Smileys & Emotion
    '😀': ['grinning', 'face', 'smile', 'happy'],
    '😃': ['grinning', 'face', 'big', 'eyes', 'happy', 'smile'],
    '😄': ['grinning', 'face', 'smiling', 'eyes', 'happy', 'smile', 'laugh'],
    '😁': ['beaming', 'face', 'smiling', 'eyes', 'happy', 'smile', 'grin'],
    '😆': ['grinning', 'squinting', 'face', 'happy', 'smile', 'laugh'],
    '😅': ['grinning', 'face', 'sweat', 'relief', 'nervous'],
    '🤣': ['rolling', 'floor', 'laughing', 'crying', 'tears', 'lol', 'rofl'],
    '😂': ['face', 'tears', 'joy', 'cry', 'laugh', 'lol'],
    '🙂': ['slightly', 'smiling', 'face', 'smile'],
    '🙃': ['upside-down', 'face', 'silly', 'sarcasm'],
    '😉': ['winking', 'face', 'wink', 'flert'],
    '😊': ['smiling', 'face', 'smiling', 'eyes', 'happy', 'smile', 'blush'],
    '😇': ['smiling', 'face', 'halo', 'angel', 'innocent'],
    '🥰': ['smiling', 'face', 'hearts', 'love', 'crush', 'adorable'],
    '😍': ['smiling', 'face', 'heart-eyes', 'love', 'crush', 'adorable'],
    '🤩': ['star-struck', 'love', 'eyes', 'stars'],
    '😘': ['face', 'blowing', 'kiss', 'love', 'smooch'],
    '😗': ['kissing', 'face', 'love', 'smooch'],
    '☺️': ['smiling', 'face', 'blush', 'happy'],
    '😚': ['kissing', 'face', 'closed', 'eyes', 'love', 'smooch'],
    '😙': ['kissing', 'face', 'smiling', 'eyes', 'love', 'smooch'],
    '🥲': ['smiling', 'face', 'tear', 'sad', 'bittersweet'],
    '😋': ['face', 'savoring', 'food', 'yum', 'delicious', 'tongue'],
    '😛': ['face', 'tongue', 'silly', 'kidding'],
    '😜': ['winking', 'face', 'tongue', 'silly', 'kidding', 'crazy'],
    '🤪': ['zany', 'face', 'silly', 'crazy', 'goofy'],
    '😝': ['squinting', 'face', 'tongue', 'silly', 'kidding'],
    '🤑': ['money-mouth', 'face', 'rich', 'dollar'],
    '🤗': ['hugging', 'face', 'hug', 'love', 'support'],
    '🤭': ['face', 'hand', 'over', 'mouth', 'oops', 'giggle'],
    '🤫': ['shushing', 'face', 'shh', 'quiet', 'silent'],
    '🤔': ['thinking', 'face', 'hmm', 'wondering'],
    '🤐': ['zipper-mouth', 'face', 'quiet', 'silent', 'secret'],
    '🤨': ['face', 'raised', 'eyebrow', 'skeptical', 'suspicious'],
    '😐': ['neutral', 'face', 'meh', 'poker'],
    '😑': ['expressionless', 'face', 'meh'],
    '😶': ['face', 'without', 'mouth', 'silent'],
    '😏': ['smirking', 'face', 'smirk', 'flirt', 'sarcastic'],
    '😒': ['unamused', 'face', 'meh', 'bored'],
    '🙄': ['face', 'rolling', 'eyes', 'bored', 'annoyed'],
    '😬': ['grimacing', 'face', 'awkward', 'nervous'],
    '🤥': ['lying', 'face', 'pinocchio', 'liar'],
    '😌': ['relieved', 'face', 'calm', 'peaceful'],
    '😔': ['pensive', 'face', 'sad', 'thoughtful'],
    '😪': ['sleepy', 'face', 'tired', 'drowsy'],
    '🤤': ['drooling', 'face', 'hungry', 'desire'],
    '😴': ['sleeping', 'face', 'zz', 'tired', 'sleep', 'dream'],
    '😷': ['face', 'medical', 'mask', 'sick', 'covid'],
    '🤒': ['face', 'thermometer', 'sick', 'fever', 'temperature'],
    '🤕': ['face', 'head', 'bandage', 'hurt', 'injury'],
    '🤢': ['nauseated', 'face', 'sick', 'vomit'],
    '🤮': ['face', 'vomiting', 'sick', 'puke'],
    '🤧': ['sneezing', 'face', 'sick', 'cold'],
    '🥵': ['hot', 'face', 'sweating', 'heat'],
    '🥶': ['cold', 'face', 'freezing', 'ice'],
    '🥴': ['woozy', 'face', 'dizzy', 'drunk'],
    '😵': ['dizzy', 'face', 'dead'],
    '🤯': ['exploding', 'head', 'mind-blown', 'shocked'],
    '🤠': ['cowboy', 'hat', 'face', 'western'],
    '🥳': ['partying', 'face', 'celebration', 'birthday'],
    '🥸': ['disguised', 'face', 'mask'],
    '😎': ['smiling', 'face', 'sunglasses', 'cool', 'sun'],
    '🤓': ['nerd', 'face', 'glasses', 'smart'],
    '🧐': ['face', 'monocle', 'fancy', 'investigate'],
    '😕': ['confused', 'face', 'hmmm'],
    '😟': ['worried', 'face', 'concerned'],
    '🙁': ['slightly', 'frowning', 'face', 'sad'],
    '☹️': ['frowning', 'face', 'sad'],
    '😮': ['face', 'open', 'mouth', 'surprise', 'wow'],
    '😯': ['hushed', 'face', 'surprise', 'quiet'],
    '😲': ['astonished', 'face', 'shocked', 'omg'],
    '😳': ['flushed', 'face', 'embarrassed', 'blush'],
    '🥺': ['pleading', 'face', 'puppy', 'eyes', 'begging'],
    '😦': ['frowning', 'face', 'open', 'mouth', 'scared', 'surprise'],
    '😧': ['anguished', 'face', 'pain', 'suffering'],
    '😨': ['fearful', 'face', 'scared', 'afraid'],
    '😰': ['anxious', 'face', 'sweat', 'nervous'],
    '😥': ['sad', 'butt', 'relieved', 'face', 'sweat', 'phew'],
    '😢': ['crying', 'face', 'sad', 'tear'],
    '😭': ['loudly', 'crying', 'face', 'sad', 'sob'],
    '😱': ['face', 'screaming', 'fear', 'scared', 'horror'],
    '😖': ['confounded', 'face', 'frustrated'],
    '😣': ['persevering', 'face', 'struggling', 'strain'],
    '😞': ['disappointed', 'face', 'sad', 'regret'],
    '😓': ['downcast', 'face', 'sweat', 'sad', 'nervous'],
    '😩': ['weary', 'face', 'tired', 'exhausted'],
    '😫': ['tired', 'face', 'exhausted'],
    '🥱': ['yawning', 'face', 'tired', 'sleepy'],
    '😤': ['face', 'steam', 'nose', 'angry', 'mad'],
    '😡': ['pouting', 'face', 'angry', 'mad', 'red'],
    '😠': ['angry', 'face', 'mad'],
    '🤬': ['face', 'symbols', 'mouth', 'swearing', 'cursing', 'angry'],
    '😈': ['smiling', 'face', 'horns', 'devil', 'evil'],
    '👿': ['angry', 'face', 'horns', 'devil', 'evil'],
    '💀': ['skull', 'death', 'dead'],
    '☠️': ['skull', 'crossbones', 'death', 'danger', 'pirate'],
    '💩': ['pile', 'poo', 'poop', 'shit'],
    '🤡': ['clown', 'face', 'funny', 'creepy'],
    '👹': ['ogre', 'monster', 'japanese'],
    '👺': ['goblin', 'monster', 'japanese'],
    '👻': ['ghost', 'spooky', 'halloween'],
    '👽': ['alien', 'ufo', 'extraterrestrial'],
    '👾': ['alien', 'monster', 'game', 'retro'],
    '🤖': ['robot', 'bot'],
    '😺': ['grinning', 'cat', 'smile', 'happy'],
    '😸': ['grinning', 'cat', 'smiling', 'eyes', 'happy'],
    '😹': ['cat', 'tears', 'joy', 'cry', 'laugh'],
    '😻': ['smiling', 'cat', 'heart-eyes', 'love'],
    '😼': ['cat', 'wry', 'smile', 'smirk'],
    '😽': ['kissing', 'cat', 'love'],
    '🙀': ['weary', 'cat', 'scared', 'shocked'],
    '😿': ['crying', 'cat', 'sad'],
    '😾': ['pouting', 'cat', 'angry'],
    '🙈': ['see-no-evil', 'monkey', 'hide'],
    '🙉': ['hear-no-evil', 'monkey'],
    '🙊': ['speak-no-evil', 'monkey'],
    '💋': ['kiss', 'mark', 'lips', 'love'],
    '💌': ['love', 'letter', 'email', 'heart'],
    '💘': ['heart', 'arrow', 'love', 'cupid'],
    '💝': ['heart', 'ribbon', 'gift', 'love'],
    '💖': ['sparkling', 'heart', 'love'],
    '💗': ['growing', 'heart', 'love', 'pulse'],
    '💓': ['beating', 'heart', 'love', 'pulse'],
    '💞': ['revolving', 'hearts', 'love'],
    '💕': ['two', 'hearts', 'love'],
    '💟': ['heart', 'decoration', 'love'],
    '❣️': ['heart', 'exclamation', 'love'],
    '💔': ['broken', 'heart', 'sad', 'breakup'],
    '❤️': ['red', 'heart', 'love'],
    '🧡': ['orange', 'heart', 'love'],
    '💛': ['yellow', 'heart', 'love'],
    '💚': ['green', 'heart', 'love'],
    '💙': ['blue', 'heart', 'love'],
    '💜': ['purple', 'heart', 'love'],
    '🤎': ['brown', 'heart', 'love'],
    '🖤': ['black', 'heart', 'love', 'goth'],
    '🤍': ['white', 'heart', 'love', 'peace'],
    '💯': ['hundred', 'points', 'score', 'perfect'],
    '💢': ['anger', 'symbol', 'mad'],
    '💥': ['collision', 'boom', 'explode'],
    '💫': ['dizzy', 'star', 'sparkle'],
    '💦': ['sweat', 'droplets', 'water'],
    '💨': ['dashing', 'away', 'wind', 'fast'],
    '🕳️': ['hole'],
    '💣': ['bomb', 'explode'],
    '💬': ['speech', 'balloon', 'chat', 'message'],
    '👁️‍🗨️': ['eye', 'speech', 'bubble'],
    '🗨️': ['left', 'speech', 'bubble'],
    '🗯️': ['right', 'anger', 'bubble'],
    '💭': ['thought', 'balloon', 'think', 'dream'],
    '💤': ['zzz', 'sleep', 'sleeping'],

    // People & Body
    '👋': ['waving', 'hand', 'hello', 'bye'],
    '🤚': ['raised', 'back', 'hand'],
    '🖐️': ['hand', 'fingers', 'splayed'],
    '✋': ['raised', 'hand', 'stop', 'high-five'],
    '🖖': ['vulcan', 'salute', 'star', 'trek', 'prosper'],
    '👌': ['ok', 'hand', 'okay', 'perfect'],
    '🤌': ['pinched', 'fingers', 'italian'],
    '🤏': ['pinching', 'hand', 'small', 'little'],
    '✌️': ['victory', 'hand', 'peace'],
    '🤞': ['crossed', 'fingers', 'luck'],
    '🤟': ['love-you', 'gesture', 'ily'],
    '🤘': ['sign', 'horns', 'rock', 'metal'],
    '🤙': ['call', 'me', 'hand', 'phone'],
    '👈': ['backhand', 'index', 'pointing', 'left'],
    '👉': ['backhand', 'index', 'pointing', 'right'],
    '👆': ['backhand', 'index', 'pointing', 'up'],
    '🖕': ['middle', 'finger', 'rude'],
    '👇': ['backhand', 'index', 'pointing', 'down'],
    '☝️': ['index', 'pointing', 'up'],
    '👍': ['thumbs', 'up', 'approve', 'like', 'good', 'yes'],
    '👎': ['thumbs', 'down', 'disapprove', 'dislike', 'bad', 'no'],
    '✊': ['raised', 'fist', 'power'],
    '👊': ['oncoming', 'fist', 'punch'],
    '🤛': ['left-facing', 'fist', 'punch'],
    '🤜': ['right-facing', 'fist', 'punch'],
    '👏': ['clapping', 'hands', 'applause'],
    '🙌': ['raising', 'hands', 'celebration'],
    '👐': ['open', 'hands'],
    '🤲': ['palms', 'up', 'together', 'pray'],
    '🤝': ['handshake', 'deal', 'agree'],
    '🙏': ['folded', 'hands', 'pray', 'please', 'thanks'],
    '✍️': ['writing', 'hand'],
    '💅': ['nail', 'polish', 'manicure'],
    '🤳': ['selfie'],
    '💪': ['flexed', 'biceps', 'muscle', 'strong'],
    '🦾': ['mechanical', 'arm'],
    '🦿': ['mechanical', 'leg'],
    '🦵': ['leg'],
    '🦶': ['foot'],
    '👂': ['ear', 'listen'],
    '🦻': ['ear', 'hearing', 'aid'],
    '👃': ['nose', 'smell'],
    '🧠': ['brain', 'smart'],
    '🫀': ['anatomical', 'heart'],
    '🫁': ['lungs'],
    '🦷': ['tooth', 'dentist'],
    '🦴': ['bone'],
    '👀': ['eyes', 'look', 'see'],
    '👁️': ['eye'],
    '👅': ['tongue'],
    '👄': ['mouth', 'lips'],
    '👶': ['baby', 'child'],
    '🧒': ['child', 'kid'],
    '👦': ['boy'],
    '👧': ['girl'],
    '🧑': ['person', 'human'],
    '👱': ['person', 'blond', 'hair'],
    '👨': ['man'],
    '🧔': ['person', 'beard'],
    '👩': ['woman'],
    '🧓': ['older', 'person'],
    '👴': ['old', 'man'],
    '👵': ['old', 'woman'],
    '🙍': ['person', 'frowning'],
    '🙎': ['person', 'pouting'],
    '🙅': ['person', 'gesturing', 'no'],
    '🙆': ['person', 'gesturing', 'ok'],
    '💁': ['person', 'tipping', 'hand', 'sassy'],
    '🙋': ['person', 'raising', 'hand'],
    '🧏': ['deaf', 'person'],
    '🙇': ['person', 'bowing', 'apology'],
    '🤦': ['person', 'facepalming', 'doh'],
    '🤷': ['person', 'shrugging', 'idk'],
    '👮': ['police', 'officer', 'cop'],
    '🕵️': ['detective', 'spy'],
    '💂': ['guard'],
    '🥷': ['ninja'],
    '👷': ['construction', 'worker'],
    '🤴': ['prince'],
    '👸': ['princess'],
    '👳': ['person', 'turban'],
    '👲': ['person', 'skullcap'],
    '🧕': ['woman', 'headscarf'],
    '🤵': ['person', 'tuxedo', 'groom'],
    '👰': ['person', 'veil', 'bride'],
    '🤰': ['pregnant', 'woman'],
    '🤱': ['breast-feeding'],
    '👼': ['baby', 'angel'],
    '🎅': ['santa', 'claus'],
    '🤶': ['mrs', 'claus'],
    '🦸': ['superhero'],
    '🦹': ['supervillain'],
    '🧙': ['mage', 'wizard'],
    '🧚': ['fairy'],
    '🧛': ['vampire'],
    '🧜': ['merperson', 'mermaid'],
    '🧝': ['elf'],
    '🧞': ['genie'],
    '🧟': ['zombie'],
    '💆': ['person', 'getting', 'massage'],
    '💇': ['person', 'getting', 'haircut'],
    '🚶': ['person', 'walking'],
    '🧍': ['person', 'standing'],
    '🧎': ['person', 'kneeling'],
    '🏃': ['person', 'running'],
    '💃': ['woman', 'dancing'],
    '🕺': ['man', 'dancing'],
    '🕴️': ['person', 'suit', 'levitating'],
    '👯': ['people', 'partying', 'bunny'],
    '🧖': ['person', 'steamy', 'room', 'sauna'],
    '👭': ['women', 'holding', 'hands'],
    '👫': ['woman', 'man', 'holding', 'hands'],
    '👬': ['men', 'holding', 'hands'],
    '💏': ['kiss'],
    '💑': ['couple', 'heart'],
    '👪': ['family'],
    '👨‍👩‍👦': ['family', 'man', 'woman', 'boy'],
    '👨‍👩‍👧': ['family', 'man', 'woman', 'girl'],
    '👨‍👩‍👧‍👦': ['family', 'man', 'woman', 'girl', 'boy'],
    '👨‍👩‍👦‍👦': ['family', 'man', 'woman', 'boy', 'boy'],

    // Animals & Nature
    '🐶': ['dog', 'face', 'puppy', 'pet'],
    '🐱': ['cat', 'face', 'kitten', 'pet'],
    '🐭': ['mouse', 'face'],
    '🐹': ['hamster'],
    '🐰': ['rabbit', 'face', 'bunny'],
    '🦊': ['fox'],
    '🐻': ['bear'],
    '🐼': ['panda'],
    '🐻‍❄️': ['polar', 'bear'],
    '🐨': ['koala'],
    '🐯': ['tiger', 'face'],
    '🦁': ['lion'],
    '🐮': ['cow', 'face'],
    '🐷': ['pig', 'face'],
    '🐽': ['pig', 'nose'],
    '🐸': ['frog'],
    '🐵': ['monkey', 'face'],
    '🐒': ['monkey'],
    '🐔': ['chicken'],
    '🐧': ['penguin'],
    '🐦': ['bird'],
    '🐤': ['baby', 'chick'],
    '🐣': ['hatching', 'chick'],
    '🐥': ['front-facing', 'baby', 'chick'],
    '🦆': ['duck'],
    '🦅': ['eagle'],
    '🦉': ['owl'],
    '🦇': ['bat'],
    '🐺': ['wolf'],
    '🐗': ['boar'],
    '🐴': ['horse', 'face'],
    '🦄': ['unicorn'],
    '🐝': ['honeybee', 'bee'],
    '🪱': ['worm'],
    '🐛': ['bug'],
    '🦋': ['butterfly'],
    'snail': ['snail'], // 🐌 missed in mapping but char is sufficient?
    '🐌': ['snail'],
    '🐞': ['lady_beetle', 'ladybug'],
    '🐜': ['ant'],
    '🪰': ['fly'],
    '🪲': ['beetle'],
    '🪳': ['cockroach'],
    '🦟': ['mosquito'],
    '🦗': ['cricket'],
    '🕷️': ['spider'],
    '🕸️': ['spider', 'web'],
    '🦂': ['scorpion'],
    '🐢': ['turtle'],
    '🐍': ['snake'],
    '🦎': ['lizard'],
    '🦖': ['t-rex', 'dinosaur'],
    '🦕': ['sauropod', 'dinosaur'],
    '🐙': ['octopus'],
    '🦑': ['squid'],
    '🦐': ['shrimp'],
    '🦞': ['lobster'],
    '🦀': ['crab'],
    '🐡': ['blowfish'],
    '🐠': ['tropical', 'fish'],
    '🐟': ['fish'],
    '🐬': ['dolphin'],
    '🐳': ['spouting', 'whale'],
    '🐋': ['whale'],
    '🦈': ['shark'],
    '🐊': ['crocodile'],
    '🐅': ['tiger'],
    '🐆': ['leopard'],
    '🦓': ['zebra'],
    '🦍': ['gorilla'],
    '🦧': ['orangutan'],
    '🦣': ['mammoth'],
    '🐘': ['elephant'],
    '🦛': ['hippopotamus'],
    '🦏': ['rhinoceros'],
    '🐪': ['camel', 'one', 'hump'],
    '🐫': ['camel', 'two', 'humps'],
    '🦒': ['giraffe'],
    '🦘': ['kangaroo'],
    '🦬': ['bison'],
    '🐃': ['water', 'buffalo'],
    '🐂': ['ox'],
    '🐄': ['cow'],
    '🐎': ['horse'],
    '🐖': ['pig'],
    '🐏': ['ram'],
    '🐑': ['sheep'],
    '🦙': ['llama'],
    '🐐': ['goat'],
    '🦌': ['deer'],
    '🐕': ['dog'],
    '🐩': ['poodle'],
    '🦮': ['guide', 'dog'],
    '🐕‍🦺': ['service', 'dog'],
    '🐈': ['cat'],
    '🐈‍⬛': ['black', 'cat'],
    '🪶': ['feather'],
    '🐓': ['rooster'],
    '🦃': ['turkey'],
    '🦤': ['dodo'],
    '🦚': ['peacock'],
    'parrot': ['parrot'],
    '🦜': ['parrot'],
    '🦢': ['swan'],
    '🦩': ['flamingo'],
    '🕊️': ['dove', 'peace'],
    '🐇': ['rabbit', 'bunny'],
    '🦝': ['raccoon'],
    '🦨': ['skunk'],
    '🦡': ['badger'],
    '🦫': ['beaver'],
    '🦦': ['otter'],
    '🦥': ['sloth'],
    '🐁': ['mouse'],
    '🐀': ['rat'],
    '🐿️': ['chipmunk'],
    '🦔': ['hedgehog'],
    '🌵': ['cactus'],
    '🎄': ['christmas', 'tree'],
    '🌲': ['evergreen', 'tree'],
    '🌳': ['deciduous', 'tree'],
    '🌴': ['palm', 'tree'],
    '🪵': ['wood'],
    '🌱': ['seedling', 'plant'],
    '🌿': ['herb'],
    '☘️': ['shamrock'],
    '🍀': ['four', 'leaf', 'clover', 'luck'],
    '🎍': ['pine', 'decoration'],
    '🪴': ['potted', 'plant'],
    '🎋': ['tanabata', 'tree'],
    '🍃': ['leaves', 'wind'],
    '🍂': ['fallen', 'leaf'],
    '🍁': ['maple', 'leaf'],
    '🍄': ['mushroom'],
    '🐚': ['shell'],
    '🪨': ['rock'],
    '🌾': ['sheaf', 'rice'],
    '💐': ['bouquet', 'flowers'],
    '🌷': ['tulip'],
    '🌹': ['rose'],
    '🥀': ['wilted', 'flower'],
    '🌺': ['hibiscus'],
    '🌸': ['cherry', 'blossom'],
    '🌼': ['blossom'],
    '🌻': ['sunflower'],
    '🌞': ['sun', 'face'],
    '🌝': ['full', 'moon', 'face'],
    '🌛': ['first', 'quarter', 'moon', 'face'],
    '🌜': ['last', 'quarter', 'moon', 'face'],
    '🌚': ['new', 'moon', 'face'],
    '🌕': ['full', 'moon'],
    '🌖': ['waning', 'gibbous', 'moon'],
    '🌗': ['last', 'quarter', 'moon'],
    '🌘': ['waning', 'crescent', 'moon'],
    '🌑': ['new', 'moon'],
    '🌒': ['waxing', 'crescent', 'moon'],
    '🌓': ['first', 'quarter', 'moon'],
    '🌔': ['waxing', 'gibbous', 'moon'],
    '🌙': ['crescent', 'moon'],
    '🌎': ['globe', 'americas'],
    '🌍': ['globe', 'europe', 'africa'],
    '🌏': ['globe', 'asia', 'australia'],
    '🪐': ['ringed', 'planet'],
    '⭐': ['star'],
    '🌟': ['glowing', 'star'],
    '✨': ['sparkles'],
    '⚡': ['high', 'voltage', 'lightning'],
    '☄️': ['comet'],
    '🔥': ['fire', 'hot', 'flame'],
    '🌪️': ['tornado'],
    '🌈': ['rainbow'],
    '☀️': ['sun'],
    '🌤️': ['sun', 'small', 'cloud'],
    '⛅': ['sun', 'behind', 'cloud'],
    '🌥️': ['sun', 'large', 'cloud'],
    '☁️': ['cloud'],
    '🌦️': ['sun', 'rain'],
    '🌧️': ['cloud', 'rain'],
    '⛈️': ['cloud', 'lightning', 'rain'],
    '🌩️': ['cloud', 'lightning'],
    '🌨️': ['cloud', 'snow'],
    '❄️': ['snowflake'],
    '☃️': ['snowman'],
    '⛄': ['snowman', 'without', 'snow'],
    '🌬️': ['wind', 'face'],
    '💧': ['droplet', 'water'],
    '☔': ['umbrella', 'rain'],
    '☂️': ['umbrella'],
    '🌊': ['wave', 'ocean'],
    '🌫️': ['fog'],

    // Food & Drink (Partial, common ones)
    '🍇': ['grapes'],
    '🍈': ['melon'],
    '🍉': ['watermelon'],
    '🍊': ['tangerine', 'orange'],
    '🍋': ['lemon'],
    '🍌': ['banana'],
    '🍍': ['pineapple'],
    '🥭': ['mango'],
    '🍎': ['red', 'apple'],
    '🍏': ['green', 'apple'],
    '🍐': ['pear'],
    '🍑': ['peach', 'butt', 'ass'],
    '🍒': ['cherries'],
    '🍓': ['strawberry'],
    '🫐': ['blueberries'],
    '🥝': ['kiwi'],
    '🍅': ['tomato'],
    '🫒': ['olive'],
    '🥥': ['coconut'],
    '🥑': ['avocado'],
    '🍆': ['eggplant'],
    '🥔': ['potato'],
    '🥕': ['carrot'],
    '🌽': ['corn'],
    '🌶️': ['hot', 'pepper', 'spicy'],
    '🫑': ['bell', 'pepper'],
    '🥒': ['cucumber'],
    '🥬': ['leafy', 'green'],
    '🥦': ['broccoli'],
    '🧄': ['garlic'],
    '🧅': ['onion'],
    '🥜': ['peanuts'],
    '🌰': ['chestnut'],
    '🍞': ['bread'],
    '🥐': ['croissant', 'quaso'],
    '🥖': ['baguette'],
    '🫓': ['flatbread'],
    '🥨': ['pretzel'],
    '🥯': ['bagel'],
    '🥞': ['pancakes'],
    '🧇': ['waffle'],
    '🧀': ['cheese'],
    '🍖': ['meat', 'bone'],
    '🍗': ['poultry', 'leg', 'chicken'],
    '🥩': ['cut', 'meat', 'steak'],
    '🥓': ['bacon'],
    '🍔': ['hamburger', 'burger'],
    '🍟': ['french', 'fries'],
    '🍕': ['pizza'],
    '🌭': ['hot', 'dog'],
    '🥪': ['sandwich'],
    '🌮': ['taco'],
    '🌯': ['burrito'],
    '🫔': ['tamale'],
    '🥙': ['stuffed', 'flatbread', 'pita'],
    '🧆': ['falafel'],
    '🥚': ['egg'],
    '🍳': ['cooking'],
    '🥘': ['shallow', 'pan', 'food'],
    '🍲': ['pot', 'food'],
    '🫕': ['fondue'],
    '🥣': ['bowl', 'spoon'],
    '🥗': ['green', 'salad'],
    '🍿': ['popcorn'],
    '🧈': ['butter'],
    '🧂': ['salt'],
    '🥫': ['canned', 'food'],
    '🍱': ['bento', 'box'],
    '🍘': ['rice', 'cracker'],
    '🍙': ['rice', 'ball'],
    '🍚': ['cooked', 'rice'],
    '🍛': ['curry', 'rice'],
    '🍜': ['steaming', 'bowl', 'noodles', 'ramen'],
    '🍝': ['spaghetti', 'pasta'],
    '🍠': ['roasted', 'sweet', 'potato'],
    '🍢': ['oden'],
    '🍣': ['sushi'],
    '🍤': ['fried', 'shrimp', 'tempura'],
    '🍥': ['fish', 'cake'],
    '🥮': ['moon', 'cake'],
    '🍡': ['dango'],
    '🥟': ['dumpling'],
    '🥠': ['fortune', 'cookie'],
    '🥡': ['takeout', 'box'],
    '🦪': ['oyster'],
    '🍦': ['soft', 'ice', 'cream'],
    '🍧': ['shaved', 'ice'],
    '🍨': ['ice', 'cream'],
    '🍩': ['doughnut'],
    '🍪': ['cookie'],
    '🎂': ['birthday', 'cake'],
    '🍰': ['shortcake'],
    '🧁': ['cupcake'],
    '🥧': ['pie'],
    '🍫': ['chocolate', 'bar'],
    '🍬': ['candy'],
    '🍭': ['lollipop'],
    '🍮': ['custard'],
    '🍯': ['honey', 'pot'],
    '🍼': ['baby', 'bottle'],
    '🥛': ['glass', 'milk'],
    '☕': ['hot', 'beverage', 'coffee', 'tea'],
    '🫖': ['teapot'],
    '🍵': ['teacup'],
    '🍶': ['sake'],
    '🍾': ['champagne'],
    '🍷': ['wine'],
    '🍸': ['cocktail'],
    '🍹': ['tropical', 'drink'],
    '🍺': ['beer', 'mug'],
    '🍻': ['clinking', 'beer', 'mugs'],
    '🥂': ['clinking', 'glasses', 'cheers'],
    '🥃': ['tumbler', 'glass', 'whiskey'],
    '🥤': ['cup', 'straw'],
    '🧋': ['bubble', 'tea'],
    '🧃': ['beverage', 'box', 'juice'],
    '🧉': ['mate'],
    '🧊': ['ice'],
    '🥢': ['chopsticks'],
    '🍽️': ['fork', 'knife', 'plate'],
    '🍴': ['fork', 'knife'],
    'spoon': ['spoon'], // 🥄
    '🥄': ['spoon'],
    '🔪': ['kitchen', 'knife'],
    '🏺': ['amphora'],

    // Activities
    '⚽': ['soccer'],
    '🏀': ['basketball'],
    '🏈': ['american', 'football'],
    '⚾': ['baseball'],
    '🥎': ['softball'],
    '🎾': ['tennis'],
    '🏐': ['volleyball'],
    '🏉': ['rugby'],
    '🥏': ['flying', 'disc', 'frisbee'],
    '🎱': ['pool', '8', 'ball'],
    '🪀': ['yo-yo'],
    '🏓': ['ping', 'pong', 'table', 'tennis'],
    '🏸': ['badminton'],
    '🏒': ['ice', 'hockey'],
    '🏑': ['field', 'hockey'],
    '🥍': ['lacrosse'],
    '🏏': ['cricket'],
    '🪃': ['boomerang'],
    '🥅': ['goal', 'net'],
    '⛳': ['flag', 'hole', 'golf'],
    'kite': ['kite'], // 🪁
    '🪁': ['kite'],
    '🏹': ['bow', 'arrow'],
    '🎣': ['fishing', 'pole'],
    '🤿': ['diving', 'mask'],
    '🥊': ['boxing', 'glove'],
    '🥋': ['martial', 'arts', 'uniform'],
    '🎽': ['running', 'shirt'],
    'skateboard': ['skateboard'], // 🛹
    '🛹': ['skateboard'],
    '🛼': ['roller', 'skate'],
    '🛷': ['sled'],
    '⛸️': ['ice', 'skate'],
    '🥌': ['curling', 'stone'],
    '🎿': ['skis'],
    '⛷️': ['skier'],
    '🏂': ['snowboarder'],
    '🪂': ['parachute'],
    '🏋️': ['person', 'lifting', 'weights'],
    '🤼': ['people', 'wrestling'],
    '🤸': ['person', 'cartwheeling'],
    '⛹️': ['person', 'bouncing', 'ball'],
    '🤺': ['person', 'fencing'],
    '🤾': ['person', 'playing', 'handball'],
    '🏌️': ['person', 'golfing'],
    '🏇': ['horse', 'racing'],
    '🧗': ['person', 'climbing'],
    '🤽': ['person', 'playing', 'water', 'polo'],
    '🏊': ['person', 'swimming'],
    '🚣': ['person', 'rowing', 'boat'],
    '🧘': ['person', 'lotus', 'position', 'yoga'],
    '🏄': ['person', 'surfing'],
    '🏆': ['trophy', 'winner'],
    '🥇': ['1st', 'place', 'medal'],
    '🥈': ['2nd', 'place', 'medal'],
    '🥉': ['3rd', 'place', 'medal'],
    '🏅': ['sports', 'medal'],
    '🎖️': ['military', 'medal'],
    '🏵️': ['rosette'],
    '🎗️': ['reminder', 'ribbon'],
    'ticket': ['ticket'], // 🎫
    '🎫': ['ticket'],
    '🎟️': ['admission', 'tickets'],
    'circus': ['circus', 'tent'], // 🎪
    '🎪': ['circus', 'tent'],
    '🤹': ['person', 'juggling'],
    '🎭': ['performing', 'arts'],
    '🩰': ['ballet', 'shoes'],
    '🎨': ['artist', 'palette'],
    '🎬': ['clapper', 'board'],
    '🎤': ['microphone'],
    '🎧': ['headphone'],
    '🎼': ['musical', 'score'],
    '🎹': ['musical', 'keyboard', 'piano'],
    '🥁': ['drum'],
    '🪘': ['long', 'drum'],
    'sax': ['saxophone'], // 🎷
    '🎷': ['saxophone'],
    '🎺': ['trumpet'],
    '🪗': ['accordion'],
    '🎸': ['guitar'],
    '🪕': ['banjo'],
    '🎻': ['violin'],
    '🎲': ['game', 'die'],
    '♟️': ['chess', 'pawn'],
    '🎯': ['bullseye', 'dart'],
    '🎳': ['bowling'],
    '🎮': ['video', 'game', 'controller'],
    '🎰': ['slot', 'machine'],
    '🧩': ['puzzle', 'piece'],

    // Travel & Places
    '🚗': ['car', 'automobile'],
    'taxi': ['taxi'], // 🚕
    '🚕': ['taxi'],
    '🚙': ['suv', 'recreational', 'vehicle'],
    'bus': ['bus'], // 🚌
    '🚌': ['bus'],
    '🚎': ['trolleybus'],
    '🏎️': ['racing', 'car'],
    '🚓': ['police', 'car'],
    '🚑': ['ambulance'],
    '🚒': ['fire', 'engine'],
    '🚐': ['minibus'],
    '🛻': ['pickup', 'truck'],
    '🚚': ['delivery', 'truck'],
    '🚛': ['articulated', 'lorry'],
    '🚜': ['tractor'],
    '🦯': ['guide', 'white', 'cane'],
    '🦽': ['manual', 'wheelchair'],
    '🦼': ['motorized', 'wheelchair'],
    'scooter': ['scooter'], // 🛴
    '🛴': ['scooter'],
    'bicycle': ['bicycle', 'bike'], // 🚲
    '🚲': ['bicycle', 'bike'],
    '🛵': ['motor', 'scooter'],
    '🏍️': ['motorcycle'],
    '🛺': ['auto', 'rickshaw'],
    '🚨': ['police', 'car', 'light', 'siren'],
    '🚔': ['oncoming', 'police', 'car'],
    '🚍': ['oncoming', 'bus'],
    '🚘': ['oncoming', 'automobile'],
    '🚖': ['oncoming', 'taxi'],
    '🚡': ['aerial', 'tramway'],
    '🚠': ['mountain', 'cableway'],
    '🚟': ['suspension', 'railway'],
    'railway': ['railway', 'car'], // 🚃
    '🚃': ['railway', 'car'],
    'tram': ['tram', 'car'], // 🚋
    '🚋': ['tram', 'car'],
    '🚞': ['mountain', 'railway'],
    '🚝': ['monorail'],
    '🚄': ['high-speed', 'train'],
    '🚅': ['bullet', 'train'],
    '🚈': ['light', 'rail'],
    '🚂': ['locomotive'],
    '🚆': ['train'],
    '🚇': ['metro'],
    '🚊': ['tram'],
    '🚉': ['station'],
    '✈️': ['airplane'],
    '🛫': ['airplane', 'departure'],
    '🛬': ['airplane', 'arrival'],
    '🛩️': ['small', 'airplane'],
    '💺': ['seat'],
    '🛰️': ['satellite'],
    '🚀': ['rocket'],
    '🛸': ['flying', 'saucer', 'ufo'],
    '🚁': ['helicopter'],
    '🛶': ['canoe'],
    '⛵': ['sailboat'],
    '🚤': ['speedboat'],
    '🛥️': ['motor', 'boat'],
    '🛳️': ['passenger', 'ship'],
    '⛴️': ['ferry'],
    '🚢': ['ship'],
    'anchor': ['anchor'], // ⚓
    '⚓': ['anchor'],
    '🪝': ['hook'],
    'fuel': ['fuel', 'pump'], // ⛽
    '⛽': ['fuel', 'pump'],
    '🚧': ['construction'],
    'traffic_light': ['traffic', 'light'], // 🚦
    '🚦': ['traffic', 'light'],
    '🚥': ['horizontal', 'traffic', 'light'],
    '🚏': ['bus', 'stop'],
    'map': ['map'], // 🗺️
    '🗺️': ['map'],
    '🗿': ['moai', 'statue'],
    '🗽': ['statue', 'liberty'],
    '🗼': ['tokyo', 'tower'],
    'castle': ['castle'], // 🏰
    '🏰': ['castle'],
    '🏯': ['japanese', 'castle'],
    'stadium': ['stadium'], // 🏟️
    '🏟️': ['stadium'],
    'ferris_wheel': ['ferris', 'wheel'], // 🎡
    '🎡': ['ferris', 'wheel'],
    '🎢': ['roller', 'coaster'],
    '🎠': ['carousel', 'horse'],
    '⛲': ['fountain'],
    '⛱️': ['umbrella', 'ground'],
    'beach': ['beach', 'umbrella'], // 🏖️
    '🏖️': ['beach', 'umbrella'],
    'island': ['island'], // 🏝️
    '🏝️': ['island'],
    'desert': ['desert'], // 🏜️
    '🏜️': ['desert'],
    'volcano': ['volcano'], // 🌋
    '🌋': ['volcano'],
    'mountain': ['mountain'], // ⛰️
    '⛰️': ['mountain'],
    'snow_capped_mountain': ['snow-capped', 'mountain'], // 🏔️
    '🏔️': ['snow-capped', 'mountain'],
    'mt_fuji': ['mount', 'fuji'], // 🗻
    '🗻': ['mount', 'fuji'],
    'camping': ['camping'], // 🏕️
    '🏕️': ['camping'],
    'tent': ['tent'], // ⛺
    '⛺': ['tent'],
    'hut': ['hut'], // 🛖
    '🛖': ['hut'],
    'house': ['house'], // 🏠
    '🏠': ['house'],
    'house_with_garden': ['house', 'garden'], // 🏡
    '🏡': ['house', 'garden'],
    'houses': ['houses'], // 🏘️
    '🏘️': ['houses'],
    'derelict_house': ['derelict', 'house'], // 🏚️
    '🏚️': ['derelict', 'house'],
    'building_construction': ['building', 'construction'], // 🏗️
    '🏗️': ['building', 'construction'],
    'factory': ['factory'], // 🏭
    '🏭': ['factory'],
    'office': ['office', 'building'], // 🏢
    '🏢': ['office', 'building'],
    'department_store': ['department', 'store'], // 🏬
    '🏬': ['department', 'store'],
    'post_office': ['post', 'office'], // 🏣
    '🏣': ['post', 'office'],
    'european_post_office': ['european', 'post', 'office'], // 🏤
    '🏤': ['european', 'post', 'office'],
    'hospital': ['hospital'], // 🏥
    '🏥': ['hospital'],
    'bank': ['bank'], // 🏦
    '🏦': ['bank'],
    'hotel': ['hotel'], // 🏨
    '🏨': ['hotel'],
    'convenience_store': ['convenience', 'store'], // 🏪
    '🏪': ['convenience', 'store'],
    'school': ['school'], // 🏫
    '🏫': ['school'],
    'love_hotel': ['love', 'hotel'], // 🏩
    '🏩': ['love', 'hotel'],
    'wedding': ['wedding'], // 💒
    '💒': ['wedding'],
    'classical_building': ['classical', 'building'], // 🏛️
    '🏛️': ['classical', 'building'],
    'church': ['church'], // ⛪
    '⛪': ['church'],
    'mosque': ['mosque'], // 🕌
    '🕌': ['mosque'],
    'synagogue': ['synagogue'], // 🕍
    '🕍': ['synagogue'],
    'hindu_temple': ['hindu', 'temple'], // 🛕
    '🛕': ['hindu', 'temple'],
    'kaaba': ['kaaba'], // 🕋
    '🕋': ['kaaba'],
    'shinto_shrine': ['shinto', 'shrine'], // ⛩️
    '⛩️': ['shinto', 'shrine'],
    'railway_track': ['railway', 'track'], // 🛤️
    '🛤️': ['railway', 'track'],
    'motorway': ['motorway'], // 🛣️
    '🛣️': ['motorway'],
    'japan': ['map', 'japan'], // 🗾
    '🗾': ['map', 'japan'],
    'moon_ceremony': ['moon', 'viewing', 'ceremony'], // 🎑
    '🎑': ['moon', 'viewing', 'ceremony'],
    'national_park': ['national', 'park'], // 🏞️
    '🏞️': ['national', 'park'],
    'sunrise': ['sunrise'], // 🌅
    '🌅': ['sunrise'],
    'sunrise_over_mountains': ['sunrise', 'mountains'], // 🌄
    '🌄': ['sunrise', 'mountains'],
    'shooting_star': ['shooting', 'star'], // 🌠
    '🌠': ['shooting', 'star'],
    'sparkler': ['sparkler'], // 🎇
    '🎇': ['sparkler'],
    'fireworks': ['fireworks'], // 🎆
    '🎆': ['fireworks'],
    'sunset': ['sunset'], // 🌇
    '🌇': ['sunset'],
    'cityscape': ['cityscape', 'dusk'], // 🌆
    '🌆': ['cityscape', 'dusk'],
    'cityscape_at_night': ['cityscape', 'night'], // 🏙️
    '🏙️': ['cityscape', 'night'],
    'night_with_stars': ['night', 'stars'], // 🌃
    '🌃': ['night', 'stars'],
    'milky_way': ['milky', 'way'], // 🌌
    '🌌': ['milky', 'way'],
    'bridge': ['bridge', 'night'], // 🌉
    '🌉': ['bridge', 'night'],
    'foggy': ['foggy'], // 🌁
    '🌁': ['foggy'],

    // Objects
    '💻': ['laptop', 'computer'],
    '📱': ['mobile', 'phone'],
    '🔨': ['hammer', 'tool'],
    '⚙️': ['gear', 'settings'],
    '💡': ['light', 'bulb', 'idea'],
    '🎉': ['party', 'popper', 'celebration'],
    '🎁': ['wrapped', 'gift', 'present'],
    '🎈': ['balloon'],
    '🔑': ['key', 'password'],
    '🔒': ['lock', 'secure'],

    // Symbols

    '✅': ['check', 'mark', 'button', 'green'],
    '❌': ['cross', 'mark', 'red'],
    '⚠️': ['warning', 'sign'],
    '⛔': ['no', 'entry'],

    // Flags - Generic fallback for flags
    '🏳️': ['white', 'flag', 'surrender'],
    '🏳️‍🌈': ['rainbow', 'flag', 'pride', 'lgbt'],
    '🇺🇸': ['us', 'flag', 'united', 'states', 'america', 'usa'],
    '🇬🇧': ['uk', 'flag', 'united', 'kingdom', 'britain'],
};
