// Auto-generated by shadcn-angular CLI. Do not edit manually.
import type { ShortcutBindingService, ShortcutDefinition } from '@/components/lib/shortcut-binding.service';

export const GENERATED_SHORTCUT_CATALOG: ReadonlyArray<{
  componentName: string;
  definitions: ReadonlyArray<ShortcutDefinition>;
}> = [

];

export function registerGeneratedShortcutCatalog(shortcuts: ShortcutBindingService): void {
  for (const entry of GENERATED_SHORTCUT_CATALOG) {
    shortcuts.defineShortcuts(entry.componentName, [...entry.definitions]);
  }
}
