// Auto-generated by shadcn-angular CLI. Do not edit manually.
import type { ShortcutBindingService, ShortcutDefinition } from '@/components/lib/shortcut-binding.service';
import { RICH_TEXT_SHORTCUT_DEFINITIONS } from '@/components/ui/rich-text-editor/rich-text-editor.component';

export const GENERATED_SHORTCUT_CATALOG: ReadonlyArray<{
  componentName: string;
  definitions: ReadonlyArray<ShortcutDefinition>;
}> = [
  { componentName: 'rich-text-editor', definitions: RICH_TEXT_SHORTCUT_DEFINITIONS },
];

export function registerGeneratedShortcutCatalog(shortcuts: ShortcutBindingService): void {
  for (const entry of GENERATED_SHORTCUT_CATALOG) {
    shortcuts.defineShortcuts(entry.componentName, [...entry.definitions]);
  }
}
