import fs from 'fs-extra';
import path from 'node:path';
import type { Config } from './config.js';
import { resolveProjectPath, aliasToProjectPath } from './paths.js';

export interface ShortcutRegistryEntry {
    exportName: string;
    componentName: string;
    sourceFile: string;
}

function getShortcutRegistryIndexPath(cwd: string, config: Config): string {
    const libDir = resolveProjectPath(cwd, aliasToProjectPath(config.aliases.utils));
    return path.join(libDir, 'shortcut-registry.index.ts');
}

export async function writeShortcutRegistryIndex(
    cwd: string,
    config: Config,
    entries: ShortcutRegistryEntry[],
): Promise<string> {
    const registryPath = getShortcutRegistryIndexPath(cwd, config);
    await fs.ensureDir(path.dirname(registryPath));

    const uniqueEntries = Array.from(new Map(entries.map(entry => [entry.exportName, entry])).values())
        .sort((a, b) => a.exportName.localeCompare(b.exportName));

    const uiAlias = config.aliases.ui;
    const shortcutServiceImport = `${config.aliases.utils}/shortcut-binding.service`;

    const imports = uniqueEntries
        .map(entry => {
            const importPath = `${uiAlias}/${entry.sourceFile.replace(/\.ts$/, '')}`;
            return `import { ${entry.exportName} } from '${importPath}';`;
        })
        .join('\n');

    const catalogItems = uniqueEntries
        .map(entry => `  { componentName: '${entry.componentName}', definitions: ${entry.exportName} },`)
        .join('\n');

    const content = `// Auto-generated by shadcn-angular CLI. Do not edit manually.
import type { ShortcutBindingService, ShortcutDefinition } from '${shortcutServiceImport}';
${imports ? `${imports}\n` : ''}
export const GENERATED_SHORTCUT_CATALOG: ReadonlyArray<{
  componentName: string;
  definitions: ReadonlyArray<ShortcutDefinition>;
}> = [
${catalogItems}
];

export function registerGeneratedShortcutCatalog(shortcuts: ShortcutBindingService): void {
  for (const entry of GENERATED_SHORTCUT_CATALOG) {
    shortcuts.defineShortcuts(entry.componentName, [...entry.definitions]);
  }
}
`;

    await fs.writeFile(registryPath, content);
    return registryPath;
}
