/**
 * Generates the per-instance theme presets written into the stylesheets of the
 * components that expose a `theme` input.
 *
 * The colour values live in ONE place — the CLI's `themeColors` table, which
 * `init` and `change-theme` also write from — so a `theme="red"` editor and an
 * app switched to red with `change-theme` can never disagree. Component sources
 * cannot import CLI code, hence a generated block plus a drift check instead of
 * an import.
 */
import { themeColors, type ThemeColor } from '../src/templates/styles.js';

/** Stylesheets (repo-relative) that carry the generated block. */
export const THEMED_STYLESHEETS = [
    'packages/components/ui/rich-text-editor/rich-text-editor.component.css',
    'packages/components/ui/data-table/data-table.component.css',
] as const;

export const START_MARKER = '/* theme-presets:start — generated by `npm run themes:sync`, do not edit */';
export const END_MARKER = '/* theme-presets:end */';

function declarations(vars: Readonly<Record<string, string>>): string {
    return Object.entries(vars).map(([name, value]) => `  ${name}: ${value};`).join('\n');
}

/**
 * The block for every preset. `:host-context(.dark)[attr]` is the form Angular's
 * emulated encapsulation expands to BOTH `.dark` on the host itself and `.dark`
 * on an ancestor; `:host-context(.dark):host([attr])` would silently drop the
 * ancestor case, which is the common one (`<html class="dark">`).
 */
export function renderThemePresetCss(): string {
    const names = Object.keys(themeColors) as ThemeColor[];
    const rules = names.flatMap((name) => [
        `:host([data-ui-theme='${name}']) {\n${declarations(themeColors[name].light)}\n}`,
        `:host-context(.dark)[data-ui-theme='${name}'] {\n${declarations(themeColors[name].dark)}\n}`,
    ]);
    return [START_MARKER, ...rules, END_MARKER].join('\n');
}

/** Replaces the marked block in `css`, or appends one when there is none yet. */
export function spliceThemePresets(css: string, block: string = renderThemePresetCss()): string {
    const start = css.indexOf(START_MARKER);
    const end = css.indexOf(END_MARKER);
    if (start === -1 || end === -1) {
        const existing = css.trimEnd();
        const prefix = existing === '' ? '' : existing + '\n\n';
        return `${prefix}${block}\n`;
    }
    return `${css.slice(0, start)}${block}${css.slice(end + END_MARKER.length)}`;
}
