/**
 * Pure helpers for `npm run release:package` — the release flow for the two
 * COMPILED npm packages, as distinct from `release-cli`'s flow for the CLI.
 *
 * Three things differ from the CLI release and drive everything here:
 *
 *  1. **Tags are per package** (`rte-v0.1.1`, `data-table-v0.2.0`), so the two
 *     packages version independently and each finds its own base ref.
 *  2. **The verdict is closure-driven.** A CLI publish is required when bundled
 *     CLI code changes; a PACKAGE release is required when anything that ends up
 *     INSIDE the tarball changes — any file of the registry closure, the package
 *     config, the theme template, or the stage/build scripts.
 *  3. **It never publishes.** npm 2FA is interactive, so the script stops after
 *     pushing the tag and prints the command for a human to run.
 *
 * Everything is value→value so the flow is testable without git or npm.
 */
import {
    ArgError,
    isBumpLevel,
    type BumpLevel,
} from './release-cli-lib.js';
import {
    PACKAGE_IDS,
    PACKAGE_NAMES,
    type PackageId,
    isPackageId,
    packageDir,
    stagedFiles,
} from './stage-package-lib.js';

export interface PackageReleaseArgs {
    readonly id: PackageId;
    readonly level: BumpLevel;
    readonly dryRun: boolean;
    readonly force: boolean;
    readonly allowDirty: boolean;
    readonly allowBranch: boolean;
    readonly skipPreflight: boolean;
    /** Test/CI escape hatch: do everything but the `git push`. */
    readonly noPush: boolean;
}

const KNOWN_FLAGS = new Set([
    '--dry-run',
    '--force',
    '--allow-dirty',
    '--allow-branch',
    '--skip-preflight',
    '--no-push',
]);

/**
 * Parses `<id> <level>` in either order, plus the release flags. Order is free
 * because `release:package -- rte patch` and `-- patch rte` are equally natural
 * at a terminal and neither is ambiguous: the ids and levels are disjoint sets.
 */
export function parsePackageArgs(argv: readonly string[]): PackageReleaseArgs {
    const flags = argv.filter((a) => a.startsWith('--'));
    const positionals = argv.filter((a) => !a.startsWith('--'));

    const unknown = flags.find((f) => !KNOWN_FLAGS.has(f));
    if (unknown) throw new ArgError(`Unknown flag: ${unknown}`);

    if (positionals.length !== 2) {
        throw new ArgError(
            `Expected exactly two arguments: <${PACKAGE_IDS.join('|')}> <patch|minor|major>. ` +
            `Got: ${positionals.join(' ') || '(none)'}`,
        );
    }

    const id = positionals.find((p) => isPackageId(p));
    if (!id || !isPackageId(id)) {
        throw new ArgError(
            `No package id in "${positionals.join(' ')}". Expected one of: ${PACKAGE_IDS.join(' | ')}`,
        );
    }
    const level = positionals.find((p) => p !== id);
    if (!level || !isBumpLevel(level)) {
        throw new ArgError(`Invalid bump level "${level ?? ''}". Expected one of: patch | minor | major`);
    }

    return {
        id,
        level,
        dryRun: flags.includes('--dry-run'),
        force: flags.includes('--force'),
        allowDirty: flags.includes('--allow-dirty'),
        allowBranch: flags.includes('--allow-branch'),
        skipPreflight: flags.includes('--skip-preflight'),
        noPush: flags.includes('--no-push'),
    };
}

/**
 * Annotated tag name. Per-package so `git describe --match '<id>-v*'` finds the
 * right base ref and the two packages never share a version line.
 */
export function packageTagName(id: PackageId, version: string): string {
    return `${id}-v${version}`;
}

/** The only two files a package release commit may contain. */
export function packageReleasePaths(id: PackageId): readonly string[] {
    return [`${packageDir(id)}/package.json`, `${packageDir(id)}/CHANGELOG.md`];
}

export function packageChangelogHeader(id: PackageId): string {
    return [
        '# Changelog',
        '',
        `All notable changes to \`${PACKAGE_NAMES[id]}\` (compiled package).`,
        'Generated by `npm run release:package` from conventional commits touching the closure.',
        '',
    ].join('\n');
}

/**
 * Every repo path whose change can alter what ships inside the tarball:
 *
 * - the staged sources themselves (the registry closure);
 * - the package's committed config (`package.json`, `README.md`,
 *   `ng-package.json`, `tsconfig.lib.json`) — the README and theme are ASSETS
 *   in the tarball, not just docs;
 * - `templates/styles.ts`, from which `theme.css` is generated;
 * - the stage / build scripts, which decide what gets copied and compiled.
 *
 * `CHANGELOG.md` is deliberately absent: it is the release's own output, so
 * counting it would make every release imply the next one.
 */
export function closurePaths(id: PackageId): ReadonlySet<string> {
    const paths = new Set<string>();
    for (const file of stagedFiles(id)) paths.add(file.src);
    for (const file of ['package.json', 'README.md', 'ng-package.json', 'tsconfig.lib.json']) {
        paths.add(`${packageDir(id)}/${file}`);
    }
    paths.add('packages/cli/src/templates/styles.ts');
    paths.add('packages/cli/scripts/stage-package.ts');
    paths.add('packages/cli/scripts/stage-package-lib.ts');
    paths.add('packages/cli/scripts/package-build.ts');
    return paths;
}

export interface PackageVerdict {
    readonly required: boolean;
    /** The changed files that triggered the verdict — printed for the maintainer. */
    readonly reasons: readonly string[];
}

/**
 * Whether a release is required: does any changed file end up in this package's
 * tarball? Path-based, so a comment-only edit to a closure file still counts —
 * that is the conservative direction (a needless release is cheap; a missing one
 * silently strands the fix).
 */
export function packageVerdict(
    changedFiles: readonly string[],
    paths: ReadonlySet<string>,
    _id: PackageId,
): PackageVerdict {
    const reasons = changedFiles.filter((file) => paths.has(file.replaceAll('\\', '/')));
    return { required: reasons.length > 0, reasons };
}
