/**
 * T-24 — argv / exit-code contract of the `stage:package` entry script.
 *
 * Subprocess tests, so they see what a maintainer sees at the terminal. Per
 * `repo-fixtures.ts`, these contribute nothing to v8 coverage of the entry —
 * that is why the entry stays thin (argv, I/O, exit codes) and all the logic
 * under test lives in `stage-package-lib.ts`.
 *
 * The real script writes into the REAL repo (`packages/<id>-package/src`), which
 * is git-ignored and regenerated by every build — so the happy-path run here is
 * safe and is exactly what `build:package` does.
 */
import path from 'node:path';
import { describe, expect, it } from 'vitest';

import { REPO_ROOT, runScript } from './repo-fixtures.js';

const SCRIPT = path.join(REPO_ROOT, 'packages/cli/scripts/stage-package.ts');

describe('stage-package entry contract (T-24)', () => {
    it('exits 1 with usage when no package id is given', () => {
        const run = runScript(SCRIPT, []);
        expect(run.status).toBe(1);
        expect(run.output).toMatch(/usage/i);
        expect(run.output).toContain('rte');
        expect(run.output).toContain('data-table');
    });

    it('exits 1 with usage on an unknown package id', () => {
        const run = runScript(SCRIPT, ['rtee']);
        expect(run.status).toBe(1);
        expect(run.output).toMatch(/unknown package/i);
        expect(run.output).toContain('rtee');
    });

    it('stages rte successfully and prints the file count', () => {
        const run = runScript(SCRIPT, ['rte']);
        expect(run.status).toBe(0);
        expect(run.output).toContain('272');
        expect(run.output).toContain('rte');
    }, 120_000);

    it('stages data-table successfully and prints its file count', () => {
        const run = runScript(SCRIPT, ['data-table']);
        expect(run.status).toBe(0);
        expect(run.output).toContain('176');
    }, 120_000);
});
