/**
 * T-24 — argv / exit-code contract of the `stage:package` entry script.
 *
 * Subprocess tests, so they see what a maintainer sees at the terminal. Per
 * `repo-fixtures.ts`, these contribute nothing to v8 coverage of the entry —
 * that is why the entry stays thin (argv, I/O, exit codes) and all the logic
 * under test lives in `stage-package-lib.ts`.
 *
 * The real script writes into the REAL repo (`packages/<id>-package/src`), which
 * is git-ignored and regenerated by every build — so the happy-path run here is
 * safe and is exactly what `build:package` does.
 */
import path from 'node:path';
import { describe, expect, it } from 'vitest';

import { REPO_ROOT, runScript } from './repo-fixtures.js';

const SCRIPT = path.join(REPO_ROOT, 'packages/cli/scripts/stage-package.ts');

describe('stage-package entry contract (T-24)', () => {
    // Missing id, typo and the audit failure are decided by runStage and pinned in
    // stage-package-cli.spec.ts; one refusal here proves the entry prints stderr
    // and turns the decision into the exit code.
    it('exits 1 with usage on an unknown package id', () => {
        const run = runScript(SCRIPT, ['rtee']);
        expect(run.status).toBe(1);
        expect(run.output).toMatch(/unknown package/i);
        expect(run.output).toContain('rtee');
        expect(run.output).toMatch(/usage/i);
    });

    // The exact file count is pinned against the registry in stage-package-lib.spec.ts;
    // here only that the real staging runs end to end through the entry. One id is
    // enough: the entry does not branch on which package it stages.
    it('stages rte successfully and prints the file count', () => {
        const run = runScript(SCRIPT, ['rte']);
        expect(run.status).toBe(0);
        expect(run.output).toMatch(/rte: staged \d+ files/);
    }, 120_000);
});
