// AUTO-GENERATED by sync-registry — do not edit; new addons join automatically.

import { RichTextActionsDirective } from '../actions';
import { RichTextAiDirective } from '../ai';
import { RichTextColorsDirective } from '../colors';
import { RichTextEmojiDirective } from '../emoji';
import { RichTextFileImportDirective } from '../file-import';
import { RichTextHistoryDirective } from '../history';
import { RichTextImagesDirective } from '../images';
import { RichTextLinksDirective } from '../links';
import { RichTextMentionsDirective } from '../mentions';
import { RichTextOutlineDirective } from '../outline';
import { RichTextSlashCommandsDirective } from '../slash-commands';
import { RichTextTablesDirective } from '../tables';
import { RichTextTypographyDirective } from '../typography';

export {
    RichTextActionsDirective,
    RichTextAiDirective,
    RichTextColorsDirective,
    RichTextEmojiDirective,
    RichTextFileImportDirective,
    RichTextHistoryDirective,
    RichTextImagesDirective,
    RichTextLinksDirective,
    RichTextMentionsDirective,
    RichTextOutlineDirective,
    RichTextSlashCommandsDirective,
    RichTextTablesDirective,
    RichTextTypographyDirective,
};

export const RTE_FULL = [
    RichTextActionsDirective,
    RichTextAiDirective,
    RichTextColorsDirective,
    RichTextEmojiDirective,
    RichTextFileImportDirective,
    RichTextHistoryDirective,
    RichTextImagesDirective,
    RichTextLinksDirective,
    RichTextMentionsDirective,
    RichTextOutlineDirective,
    RichTextSlashCommandsDirective,
    RichTextTablesDirective,
    RichTextTypographyDirective,
] as const;
